### ISSUE TITLE
[REVIEW]: idvf: Iterative Inversion of Deformation Vector Field with Adaptive Bi-residual Feedback Control

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1076]
**Submitting author:** @ailiop (<a href="http://orcid.org/0000-0002-1959-9792">Alexandros-Stavros Iliopoulos</a>)
**Repository:** <a href="https://github.com/ailiop/idvf" target ="_blank">https://github.com/ailiop/idvf</a>
**Version:** v1.0.3b
**Editor:** @arokem
**Reviewer:** @Kevin-Mattheus-Moerman
**Archive:** <a href="https://doi.org/10.5281/zenodo.2610844" target="_blank">10.5281/zenodo.2610844</a>

## Status

[![status](http://joss.theoj.org/papers/8c6d0384e916c83d5470c41249c79daf/status.svg)](http://joss.theoj.org/papers/8c6d0384e916c83d5470c41249c79daf)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/8c6d0384e916c83d5470c41249c79daf"><img src="http://joss.theoj.org/papers/8c6d0384e916c83d5470c41249c79daf/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/8c6d0384e916c83d5470c41249c79daf/status.svg)](http://joss.theoj.org/papers/8c6d0384e916c83d5470c41249c79daf)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ailiop/idvf" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@Kevin-Mattheus-Moerman, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arokem know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ailiop/idvf">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.0.3b
- [x] **Authorship:** Has the submitting author (@ailiop) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @Kevin-Mattheus-Moerman it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01076/joss.01076/10.21105.joss.01076.pdf)

**Comment by ailiop** [comment]
Hi @Kevin-Mattheus-Moerman : did you run into any difficulties with the code that I could help with by any chance? I do not mean to press, just seeing if there is anything I can do.

**Comment by Kevin-Mattheus-Moerman** [comment]
Hi @ailiop apologies for the delay. I'm starting review today. I'll let you know if there are any issues.

**Comment by Kevin-Mattheus-Moerman** [comment]
@wouterpotters would you be interested in helping with this review? Flow inversion sounds like your :tea: ?

**Comment by ailiop** [comment]
@Kevin-Mattheus-Moerman : That sounds great, thank you.

**Comment by wouterpotters** [comment]
unfortunately my knowledge on this topic is (too) limited to facilitate a
proper review. Maybe one of the CFD experts can help you out?

Best,
Wouter

Op wo 5 dec. 2018 om 09:32 schreef Kevin Mattheus Moerman <
notifications@github.com>

**Comment by Kevin-Mattheus-Moerman** [comment]
This is a well written and well documented submission. Below are my questions/comments and links to issues so far. 

__Questions__
- [ ] Can you explain why simple interpolation is not sufficient? (see issue https://github.com/ailiop/idvf/issues/2)

__General comments__
- [ ] Please add community guidelines (see issue: https://github.com/ailiop/idvf/issues/1)
- [ ] Can you please add a more complex spatially varying 3D demo? (see issue: https://github.com/ailiop/idvf/issues/3)
- [ ] Can you explain the artifacts occurring in the demos? (see issue: https://github.com/ailiop/idvf/issues/5)

__Recommendations__ 
- [ ] Consider using a larger default figure size (see issue: https://github.com/ailiop/idvf/issues/4)
- [ ] Can you include visualization of errors in the reconstructed image domain e.g. the reference image subtracted from the reconstructed reference image (e.g. like presented in https://github.com/ailiop/idvf/issues/5)? And perhaps also plotting of errors of the coordinates (e.g. after using inverse mapping on the coordinates in the deformed configuration). These errors visualize nicely and are easy to interpret.

**Comment by arokem** [comment]
@Kevin-Mattheus-Moerman : I just saw the exchange above. Do you want me to find one more reviewer for this? Looks like you have this under control 😄

**Comment by ailiop** [comment]
@Kevin-Mattheus-Moerman : Thank you very much for your detailed comments! I am sorry for not replying earlier; I will work on addressing all of your comments this week.

**Comment by arokem** [comment]
Hey @ailiop -- just making sure that you are still there? We had a brief email exchange a couple of weeks ago, and you told me that you are coming back to this. Have you had a chance to take another look and address the comments?

**Comment by ailiop** [comment]
Dear @arokem and @Kevin-Mattheus-Moerman -- I am really sorry for my unacceptably long absence from this thread. I cannot apologize enough, but I want to sincerely thank @arokem for his patience and @Kevin-Mattheus-Moerman for his thorough and very helpful review.

I have updated the idvf repository to release v1.0.2 and posted responses to the issues opened by @Kevin-Mattheus-Moerman.

**Comment by labarba** [comment]
👋 @Kevin-Mattheus-Moerman — It looks like we're now waiting for you to have a look at the revisions and responses posted by the author. Can you give us a status update?

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks for the reminder @labarba I'll resume work on this on Wednesday.

**Comment by Kevin-Mattheus-Moerman** [comment]
@ailiop thanks for implementing lots of my suggestions. 

When I try to run `demo_inversion_3d_z0.m` I get this error: 

```
Error using reshape
To RESHAPE the number of elements must not change.

Error in util.imageGridSmooth (line 84)
    width     = reshape( width    , [1, nDim] );

Error in demo_inversion_3d_z0 (line 118)
IRef = util.imageGridSmooth( [szDom zdim], [15 15 5] );
```

It points to: 
```matlab
IRef = util.imageGridSmooth( [szDom zdim], [15 15 5] );
```

Can you check what is going on?

**Comment by ailiop** [comment]
@Kevin-Mattheus-Moerman : Thank you for pointing this out---and for all of your suggestions, which were very helpful!

I have fixed the offending line in the repository (removing `zdim`).  The demo should run without issue now.  I do apologize for the error, it should not have slipped through.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01076/joss.01076/10.21105.joss.01076.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1002/mp.12962 is OK
- 10.5281/zenodo.1476602 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@ailiop one box above remains unticked i.e. the one relating to automated testing. If the demos test the full functionality perhaps you can create a single script called `test_idvf.m`which simply calls all demos and runs them consecutively.

**Comment by ailiop** [comment]
@Kevin-Mattheus-Moerman : Thank you for all your help!  I have committed such a testing script exactly per your suggestion.

**Comment by Kevin-Mattheus-Moerman** [comment]
@arokem I've just ticked all the boxes and recommend this work is accepted in JOSS. Thanks for the opportunity to review this interesting work.

**Comment by arokem** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01076/joss.01076/10.21105.joss.01076.pdf)

**Comment by arokem** [comment]
@Kevin-Mattheus-Moerman : thanks for reviewing! 

@ailiop : your paper is ready to be accepted. Could you please make an archive of the accepted version of the software (e.g., using [zenodo](https://zenodo.org)) and post the DOI here? Once I register the archive for your software we will be able to do the final checks with the EIC to accept your paper.

**Comment by ailiop** [comment]
@arokem : I have just made a new release (v1.0.3).  The version-specific Zenodo archive DOI is 10.5281/zenodo.2605532.  (In case you need it, the version-less DOI which always points to the latest version is 10.5281/zenodo.1476601.)  Thank you for all your help!

@Kevin-Mattheus-Moerman : Thank you once again for your effort in reviewing this work!

**Comment by ailiop** [comment]
@arokem : I just realized that I had forgotten to update the release version tag to v1.0.3 in the `codemeta.json` metadata.  I am sorry I did not notice that yesterday before archiving the release.  Should I delete and re-create the release to make sure the JSON metadata are consistent with it before you run through the final checks you mentioned?

**Comment by arokem** [comment]
@ailiop : If it's not too much to ask, please do update the codemeta file and make a new release, so that everything's consistent and then create a new archive with this version. Thanks!

**Comment by ailiop** [comment]
@arokem : No problem at all, I figured it might be an issue.  I just created a new release (v1.0.3b) with a corrected `codemeta.json` file.  The Zenodo DOI for v1.0.3b is 10.5281/zenodo.2610844.

**Comment by arokem** [comment]
@whedon set 10.5281/zenodo.2610844 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2610844" target="_blank">10.5281/zenodo.2610844</a> is the archive.

**Comment by arokem** [comment]
@whedon set v1.0.3b as version

**Comment by whedon** [comment]
OK. v1.0.3b is the version.

**Comment by arokem** [comment]
OK. This is ready to be accepted. 

One of the EIC will come by, make comments if they have any, and finish the process.

**Comment by danielskatz** [comment]
thanks to @arokem for editing and @Kevin-Mattheus-Moerman for reviewing!!

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/589

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/589, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1002/mp.12962 is OK
- 10.5281/zenodo.1476602 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/590
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01076](https://doi.org/10.21105/joss.01076)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01076/status.svg)](https://doi.org/10.21105/joss.01076)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01076">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01076/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01076/status.svg
   :target: https://doi.org/10.21105/joss.01076
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01076/status.svg)](https://doi.org/10.21105/joss.01076)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by ailiop** [comment]
Thank you all very much!
