### ISSUE TITLE
[REVIEW]: Ocellaris: an exactly incompressible DG FEM solver for free surface flows

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1239]
**Submitting author:** @TormodLandet (<a href="http://orcid.org/0000-0001-5070-8056">Tormod Landet</a>)
**Repository:** <a href="https://bitbucket.org/ocellarisproject/ocellaris" target ="_blank">https://bitbucket.org/ocellarisproject/ocellaris</a>
**Version:** v2019.0.2
**Editor:** @labarba
**Reviewer:** @inducer, @piyueh
**Archive:** <a href="https://doi.org/10.5281/zenodo.2601988" target="_blank">10.5281/zenodo.2601988</a>

## Status

[![status](http://joss.theoj.org/papers/cf4e4c03db671ef1caea7bc0b5d096ec/status.svg)](http://joss.theoj.org/papers/cf4e4c03db671ef1caea7bc0b5d096ec)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/cf4e4c03db671ef1caea7bc0b5d096ec"><img src="http://joss.theoj.org/papers/cf4e4c03db671ef1caea7bc0b5d096ec/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/cf4e4c03db671ef1caea7bc0b5d096ec/status.svg)](http://joss.theoj.org/papers/cf4e4c03db671ef1caea7bc0b5d096ec)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://bitbucket.org/ocellarisproject/ocellaris" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@inducer & @piyueh, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @labarba know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://bitbucket.org/ocellarisproject/ocellaris">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v2019.0.2
- [x] **Authorship:** Has the submitting author (@TormodLandet) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://bitbucket.org/ocellarisproject/ocellaris">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v2019.0.2
- [x] **Authorship:** Has the submitting author (@TormodLandet) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @inducer, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01239/joss.01239/10.21105.joss.01239.pdf)

**Comment by labarba** [comment]
👋 @inducer, @piyueh —
Thank you for agreeing to review for JOSS: we couldn't do this without you 🙏 

This is where the action happens. You both have a reviewer checklist at the top of this thread. Work your way through that, and feel free to ask questions here and to open issues in the submission repository as needed. 

[The JOSS review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html)

**Comment by TormodLandet** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01239/joss.01239/10.21105.joss.01239.pdf)

**Comment by piyueh** [comment]
@labarba @TormodLandet  Regarding the question "***Version**: Does the release version given match the GitHub release (2019.0.1)?*", should I only review this specific version? Or should I review the master branch? It appears there are some new commits in the repository after the commit that is tagged with **2019.0.0**.

**Comment by TormodLandet** [comment]
I have worked on updating the documentation since the release. There should not be any code changes as far as I remember. I can release 2019.0.2 with the current changes if that is preferable. The only change since 2019.0.1 is extending and moving the documentation to [www.ocellaris.org](https://www.ocellaris.org/) and working on the JOSS paper.

**Comment by labarba** [comment]
As the review proceeds, the author will make changes, so commits will accrue. But your review should be on the master branch, unless the author requests that we work on a separate branch for the whole review. What we don't want, though, is to confuse reviewers with more than one branch active in review.

**Comment by piyueh** [comment]
OK, I'll review the master branch

**Comment by inducer** [comment]
Here's a [marked-up copy of the paper](https://ssl.tiker.net/nextcloud/index.php/s/NZ9qeknZ3PT2HD9). I've raised a number of concerns.

On the code end (for now):

* https://bitbucket.org/ocellarisproject/ocellaris/issues/9/joss-lid-driven-cavity-example-crashes
* https://bitbucket.org/ocellarisproject/ocellaris/issues/8/joss-unclosed-file-warning

**Comment by inducer** [comment]
Also noticed that two references are missing DOIs.

**Comment by labarba** [comment]
Check out the powers of our bot…

**Comment by labarba** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.17226/5870 is OK
- 10.1007/s10915-009-9268-2 is OK
- 10.1007/s10915-011-9501-7 is OK
- 10.11588/ans.2015.100.20553 is OK
- 10.1007/978-3-642-23099-8 is OK

MISSING DOIs

- https://doi.org/10.1177/1040638717729726 may be missing for title: Ocellaris source code
- https://doi.org/10.7717/peerj.2949/fig-4 may be missing for title: The Ocellaris project web page, user guide and blog
- https://doi.org/10.2172/963444 may be missing for title: Slope limiting the velocity field in a discontinuous Galerkin divergence free two-phase flow solver
- https://doi.org/10.1063/1.168744 may be missing for title: A tensorial approach to computational continuum mechanics using object-oriented techniques
- https://doi.org/10.1016/s0021-9991(03)00298-5 may be missing for title: Gerris: a tree-based adaptive solver for the incompressible Euler equations in complex geometries
- https://doi.org/10.2172/1483828 may be missing for title: PETSc: Portable, Extensible Toolkit for Scientific Computation
- https://doi.org/10.17504/protocols.io.wv2fe8e may be missing for title: meshio
- https://doi.org/10.1109/hpcmp-ugc.2007.30 may be missing for title: The XDMF format
- https://doi.org/10.1063/1.4937536 may be missing for title: The HDF5 format

INVALID DOIs

- None
```

**Comment by piyueh** [comment]
Review tracker from @piyueh :

* [x] [Issue #7: License issue](https://bitbucket.org/ocellarisproject/ocellaris/issues/7/joss-review-apache-license-version-20)
* [ ] [Issue #11: Installation instruction](https://bitbucket.org/ocellarisproject/ocellaris/issues/11/joss-review-installation-instruction)

**Comment by TormodLandet** [comment]
Thanks for the the review and comments on the paper, @inducer! I have updated the Markdown document and pushed the changes to master.

@whedon generate pdf

Below follows answers/clarifications to some comments

### Discussion of finite volume methods

I extended and clarified this section (of "competing" methods). The intent is to show the commonly used methods (piecewise constant, first or second order, finite volume + volume of fluid) and contrast these with DG FEM (the method used in Ocellaris). The lack of Gibbs oscillations in FVM (for low order reconstructions only, of course!) is a plus, but the lack of high order without large reconstruction stencils is a negative for unstructred meshes. I do not claim that a DG FEM method is better, just that it is a fully working alternative, and many people are most familiar with the FVM methods, so comparing to these makes sense to me.

### DG FEM performance

As the cited papers show, DG FEM can be faster than continuous FEM when the approximation order increases. Ocellaris can in principle go up to very high order, but this currently only works for single-phase simulations. The C++ implementation of slope limiters for cubic or higher order polynomials is missing, so in practice only linear or quadratic elements can currently be used for two-phase flow simulations. In this range DG FEM does probably not have any computational advantages over CG FEM, so I am not claming that the method is currently very computationally efficient compared to FVM or CG FEM. What I do believe is that this direction of development (higher order DG FEM) may have advantages for two-phase flow simulations despite the greatly increased number of unknowns in the DG basis functions. Some more pieces must fall into place (VOF/level set methods targeted at advection by a higher order DG FEM velocity field, and better preconditioning for the variable density equation with jump in density field are probably the two most important) before Ocellaris can possibly be selected based on a purely computational performance, but I hope Ocellaris can serve as a testbed for some of these advances in the future.

### Higher order geometry

Ocellaris supports higher order geometry, but I have not used this much personally, and I do not test it on the CI system, so I'm not sure I want to advertise it right now.

### YAML vs Python as configuration

Using Python as a configuration and input file format has obvious benefits such as a very high degree of flexibility. I have, however, worked for some years in a team that had a core tool that used Python scripts as input files. Such files are often "throwaway" code and are given less care and documentation than "real" code. Given the posibilities, many people will construct very clever and efficient workflows, which are extremely hard for others to inspect. This is a problem for QA, sharing, and for training new users. Ocellaris can be used this way, the `Simulation.input` object can be treated as a nested dictionary and can be created entirely from code. However, I strongly prefer less flexible input files by default. This makes all files follow somewhat of the same pattern, and makes it easier to catch mistakes and learn from simulation input files written by other people. I try to introduce less flexible INI/YAML input file formats in all my projects due to my past experience. It is my goal that 95% of simulations can be configured in a compact and readable manner without introducing code into the configuration, but I do recognize the need to "drop down" into code, and the input file format allows for this. I hope it will not be used by every simulation, and that the main rigid input file layout will make it easy to mentally and programmatically "diff" two simulations, find problems, and understand the intention of the writer.

### PETSc bibtex generator (using the "-citations" option)

Done

### DOIs

Every reference now has a DOI or URL

@whedon check references

**Comment by TormodLandet** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01239/joss.01239/10.21105.joss.01239.pdf)

**Comment by inducer** [comment]
> Vada, & Braathen

- [ ] extraneous comma

**Comment by inducer** [comment]
The paper and documentation look good to me now, and the software appears to work as advertised. Once community guidelines are added, I recommend accepting the paper. As for my review checklist, since I reviewed a recent git version (762876f), I recommend rolling a new release, so that I can check off the version-related item.

**Comment by TormodLandet** [comment]
Thanks both of you for your useful comments! I updated the [community guidelines](https://www.ocellaris.org/programmers_guide/guidelines.html) with information about how to run the tests, fixed the installation instruction per the review comments and released a new version, 2019.0.2 on both PyPi and the Singularity Library.

With regards to the extraneous commas in the references, they show up in multiple places in the reference list and seem to be related to the LaTex style used by the automated Markdown->LaTeX->PDF toolchain

**Comment by inducer** [comment]
> With regards to the extraneous commas in the references, they show up in multiple places in the reference list and seem to be related to the LaTex style used by the automated Markdown->LaTeX->PDF toolchain

OK, not a deal breaker. Just figured I would point it out.

> Thanks both of you for your useful comments! I updated the community guidelines with information about how to run the tests

On that page, I recommend

* adding a heading "How to report a bug" with a direct link to the issue tracker.
* adding a heading "How to contribute a patch" with instructions on how to submit the patch. (particularly if someone doesn't already have commit rights)
* adding a heading "How to get tech support" describing how one might accomplish that.

**Comment by TormodLandet** [comment]
The development guidelines page was getting long, and was dominated by *How to contribute a patch*, so I made a new community guidelines page, more prominently featured in the documentation with your three suggested headings. I like how it is now quite clear how to engage, thank you! The new page can be seen here: https://www.ocellaris.org/community_guidelines.html

The development guidelines now has a section on how to merge code, also when you do not have write access to the repo

**Comment by inducer** [comment]
:+1:

**Comment by piyueh** [comment]
The software has an OSI approved license, sufficient documentation, clear community guidelines, and automated tests. I can successfully installed the software and run the examples to confirm the functionality. Once the concern regarding the example usage of parallel runs is resolved, I recommend accepting the paper.

Issue tracker:
* [x] [Issue #7: License issue](https://bitbucket.org/ocellarisproject/ocellaris/issues/7/joss-review-apache-license-version-20)
* [x] [Issue #11: Installation instruction](https://bitbucket.org/ocellarisproject/ocellaris/issues/11/joss-review-installation-instruction)
* [x] [Issue #12: Automated tests](https://bitbucket.org/ocellarisproject/ocellaris/issues/12/joss-review-automated-tests)
* [ ] [Issue #13: Example usage](https://bitbucket.org/ocellarisproject/ocellaris/issues/13/joss-review-example-usage)

Non-blocking issue:
[Issue #14](https://bitbucket.org/ocellarisproject/ocellaris/issues/14/joss-review-other-small-issues-in-the)

**Comment by TormodLandet** [comment]
@labarba the accepted version (2019.0.2) has been archived on Zenodo with DOI [10.5281/zenodo.2601988](http://dx.doi.org/10.5281/zenodo.2601988)
I changed the title of the paper slightly from the submitted title, hope that is OK

**Comment by labarba** [comment]
@whedon set 10.5281/zenodo.2601988 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2601988" target="_blank">10.5281/zenodo.2601988</a> is the archive.

**Comment by labarba** [comment]
@piyueh You've left one item of the review list unchecked. Are you ready to check that off?

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01239/joss.01239/10.21105.joss.01239.pdf)

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/574

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/574, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1063/1.168744 is OK
- 10.1016/S0021-9991(03)00298-5 is OK
- 10.1016/j.wavemoti.2019.01.007 is OK
- 10.1017/CBO9780511546068 is OK
- 10.17226/5870 is OK
- 10.1016/0021-9991(81)90145-5 is OK
- 10.2514/6.1979-1469 is OK
- 10.1007/s10915-009-9268-2 is OK
- 10.1007/s10915-011-9501-7 is OK
- 10.11588/ans.2015.100.20553 is OK
- 10.1007/978-3-642-23099-8 is OK
- 10.1007/978-1-4612-1986-6_8 is OK
- 10.1016/j.advwatres.2011.04.013 is OK
- 10.1145/992200.992206 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by labarba** [comment]
@whedon set v2019.0.2 as version

**Comment by whedon** [comment]
OK. v2019.0.2 is the version.

**Comment by labarba** [comment]
@TormodLandet — We're ready to publish your paper. Please give the proof one last check and confirm here that you approve the proof (if you feel like it, you could hyphenate your compound adjectives in several places).

**Comment by piyueh** [comment]
> ready

Done.

**Comment by TormodLandet** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01239/joss.01239/10.21105.joss.01239.pdf)

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1063/1.168744 is OK
- 10.1016/S0021-9991(03)00298-5 is OK
- 10.1016/j.wavemoti.2019.01.007 is OK
- 10.1017/CBO9780511546068 is OK
- 10.17226/5870 is OK
- 10.1016/0021-9991(81)90145-5 is OK
- 10.2514/6.1979-1469 is OK
- 10.1007/s10915-009-9268-2 is OK
- 10.1007/s10915-011-9501-7 is OK
- 10.11588/ans.2015.100.20553 is OK
- 10.1007/978-3-642-23099-8 is OK
- 10.1007/978-1-4612-1986-6_8 is OK
- 10.1016/j.advwatres.2011.04.013 is OK
- 10.1145/992200.992206 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/582

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/582, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
The paper has 21 references, but the XML file for the Crossref deposit lists 22 citations. I think this will cause a false citation to be counted by Crossref. Could you delete the entry from you r`.bib` file that is not being cited in the paper?

**Comment by TormodLandet** [comment]
I removed the unused reference

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/583

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/583, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1063/1.168744 is OK
- 10.1016/S0021-9991(03)00298-5 is OK
- 10.1016/j.wavemoti.2019.01.007 is OK
- 10.1017/CBO9780511546068 is OK
- 10.17226/5870 is OK
- 10.1016/0021-9991(81)90145-5 is OK
- 10.2514/6.1979-1469 is OK
- 10.1007/s10915-009-9268-2 is OK
- 10.1007/s10915-011-9501-7 is OK
- 10.11588/ans.2015.100.20553 is OK
- 10.1007/978-3-642-23099-8 is OK
- 10.1007/978-1-4612-1986-6_8 is OK
- 10.1016/j.advwatres.2011.04.013 is OK
- 10.1145/992200.992206 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/584
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01239](https://doi.org/10.21105/joss.01239)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @TormodLandet, your JOSS paper is published!

Big thanks to the reviewers, @inducer and @piyueh — we couldn't do this without you! 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01239/status.svg)](https://doi.org/10.21105/joss.01239)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01239">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01239/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01239/status.svg
   :target: https://doi.org/10.21105/joss.01239
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01239/status.svg)](https://doi.org/10.21105/joss.01239)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by labarba** [comment]
https://twitter.com/LorenaABarba/status/1110972747289636866
