### ISSUE TITLE
[REVIEW]: sbpy: A Python module for small-body planetary astronomy

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1426]
**Submitting author:** @mommermi (<a href="http://orcid.org/0000-0002-8132-778X">Michael Mommert</a>)
**Repository:** <a href="https://github.com/NASA-Planetary-Science/sbpy" target ="_blank">https://github.com/NASA-Planetary-Science/sbpy</a>
**Version:** v0.1.1
**Editor:** @xuanxu
**Reviewer:** @Juanlu001
**Archive:** <a href="https://doi.org/10.5281/zenodo.3252172" target="_blank">10.5281/zenodo.3252172</a>

## Status

[![status](http://joss.theoj.org/papers/8b8e7bb15fb4a14f80f2afd06b6ce060/status.svg)](http://joss.theoj.org/papers/8b8e7bb15fb4a14f80f2afd06b6ce060)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/8b8e7bb15fb4a14f80f2afd06b6ce060"><img src="http://joss.theoj.org/papers/8b8e7bb15fb4a14f80f2afd06b6ce060/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/8b8e7bb15fb4a14f80f2afd06b6ce060/status.svg)](http://joss.theoj.org/papers/8b8e7bb15fb4a14f80f2afd06b6ce060)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/NASA-Planetary-Science/sbpy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@Juanlu001, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @xuanxu know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/NASA-Planetary-Science/sbpy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.1.1
- [x] **Authorship:** Has the submitting author (@mommermi) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @Juanlu001 it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by Juanlu001** [comment]
Before I finish a proper review:

> Does the repository contain a plain-text LICENSE file with the contents of an OSI approved software license?

The license is stated in the README and also in https://github.com/NASA-Planetary-Science/sbpy/blob/master/licenses/LICENSE.rst. Not what I expected, but I guess it should be enough.

**Comment by mommermi** [comment]
Hi @Juanlu001, thanks for reviewing this submission! Would you prefer the `License.rst` to be on the root level (probably makes more sense on the root level anyway...)?

**Comment by Juanlu001** [comment]
I think so @mommermi! Having a `LICENSE` at the top (not sure about the extensions) makes it easier to spot and also GitHub can read the metadata from it.

**Comment by mommermi** [comment]
Ok, done! 
I created a PR (NASA-Planetary-Science/sbpy#145) that will hold all the code changes from this review.

**Comment by mommermi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01426/joss.01426/10.21105.joss.01426.pdf)

**Comment by mommermi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01426/joss.01426/10.21105.joss.01426.pdf)

**Comment by xuanxu** [comment]
@Juanlu001 What's your status with the continued review of this submission?

**Comment by Juanlu001** [comment]
@xuanxu Had a tough day at work, hopefully I will complete it this week

**Comment by xuanxu** [comment]
@Juanlu001 friendly ping :)

**Comment by Juanlu001** [comment]
Sorry all for the delay! I finished the review, having paid more attention to the orbital stuff and installation and testing procedures. Some comments:

* There seems to be [a v0.1 release](https://github.com/NASA-Planetary-Science/sbpy/releases/tag/v0.1) but [sbpy does not exist in PyPI](https://pypi.org/search/?q=sbpy). Is this intentional?
* https://github.com/NASA-Planetary-Science/sbpy/issues/151
* https://github.com/NASA-Planetary-Science/sbpy/issues/152
* https://github.com/NASA-Planetary-Science/sbpy/issues/149
* It's not entirely clear to me what's the difference between `from_horizons` and `from_mpc` in `Orbit` and `Ephem` objects. Or why there is a `Phys.from_sbdb`, but not a `Orbit.from_sbdb` (or `Ephem.from_sbdb`).
* `Orbit` methods return data in a coordinate system that is not made explicit, which can be a source of confusion. `Ephem` methods have a similar issue although I would need to look carefully at all the columns returned.
* The narrative documentation of `imageanalysis` and `thermal` are noticeably shorter than the other modules, and API docs of the latter are a bit lacking (except for `ThermalClass`)
* There _are_ automated tests, but https://github.com/NASA-Planetary-Science/sbpy/issues/150
* Also, it would be nice to describe these steps, even if they are obvious to experienced developers, in https://sbpy.readthedocs.io/en/latest/contributing.html

I left some boxes unchecked until the original authors clarify the status of the `v0.1` version, the testing issues, and the API docs of `sbpy.thermal`.

**Comment by mommermi** [comment]
Thank, @Juanlu001, for your review! I will work my way through it and hopefully finish it this week.

**Comment by mommermi** [comment]
Here are some replies to you general comments:

> There seems to be a v0.1 release but sbpy does not exist in PyPI. Is this intentional?

No, we simply haven't gotten around to register it with PyPI. Most likely we will wait for this until v0.2 is released in a few weeks.

> It's not entirely clear to me what's the difference between from_horizons and from_mpc in Orbit and Ephem objects. Or why there is a Phys.from_sbdb, but not a Orbit.from_sbdb (or Ephem.from_sbdb).

`Ephem` objects are intended to hold ephemeris data, or, more generally, data that are time-dependent. `Orbit` objects on the other side hold orbital elements. [SBDB](https://ssd.jpl.nasa.gov/sbdb.cgi) is only used to extract physical properties - although it could be used to extract orbital elements, as well. We made this decision as `Orbit.from_horizons` taps the same data source including some additional information. 

* [ ]  I already have an item on my to-do list to better explain the difference between `Ephem`, `Orbit`, and `Phys` in the docs, which should clarify the differences and why the different services have been implemented in these classes.  I added this issue as NASA-Planetary-Science/sbpy#153

> Orbit methods return data in a coordinate system that is not made explicit, which can be a source of confusion. Ephem methods have a similar issue although I would need to look carefully at all the columns returned.

* [ ] I will clarify this: NASA-Planetary-Science/sbpy#154

> The narrative documentation of imageanalysis and thermal are noticeably shorter than the other modules, and API docs of the latter are a bit lacking (except for ThermalClass)

The documentation for some of the modules (including `imageanalysis` and `thermal`) are simply skeletons as they have not yet been fully implemented. Documentation will be improved and added once the modules have been further implemented. 

> Also, it would be nice to describe these steps, even if they are obvious to experienced developers, in https://sbpy.readthedocs.io/en/latest/contributing.html

* [ ] Will do: NASA-Planetary-Science/sbpy#155

**Comment by mommermi** [comment]
@Juanlu001 I think I implemented all the changes. My replies and corresponding changes in the code are linked in the corresponding issues:

NASA-Planetary-Science/sbpy#149
NASA-Planetary-Science/sbpy#150
NASA-Planetary-Science/sbpy#152
NASA-Planetary-Science/sbpy#153
NASA-Planetary-Science/sbpy#154
NASA-Planetary-Science/sbpy#155

NASA-Planetary-Science/sbpy#151 has already been closed. 

If there is anything else I can do, please let me know!

**Comment by Juanlu001** [comment]
Excellent @mommermi! I checked all the boxes in the review and think this is good to go with https://github.com/NASA-Planetary-Science/sbpy/pull/156.

**Comment by mommermi** [comment]
Thanks, @Juanlu001! I will wait with merging NASA-Planetary-Science/sbpy#156 until the astropy core issue is fixed and the CI builds succeed again. Thanks for your detailed review!

**Comment by mommermi** [comment]
And, of course, thanks to @bsipocz, too, for her comments and help!

**Comment by xuanxu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01426/joss.01426/10.21105.joss.01426.pdf)

**Comment by xuanxu** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1051/0004-6361/201322068 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.3847/1538-3881/aafc33 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by xuanxu** [comment]
Everything looks good. @mommermi After the revision changes version 0.1 is 27 commits behind master. Could you please release a new version from the current master? 

Once you do that please create a Zenodo archive of that new version and report its DOI here (edit the Zenodo deposit metadata (title and author list) to match [the paper](https://github.com/openjournals/joss-papers/blob/joss.01426/joss.01426/10.21105.joss.01426.pdf)).

**Comment by mommermi** [comment]
Thanks, @xuanxu, it's in the works. I have to wait for our NASA program officer (who is in charge of the github organization under which sbpy resides) to enable third-party access to the repo for zenodo. I'll ping you once we have the doi.

**Comment by mommermi** [comment]
Ok, the latest version is registered with zenodo. The DOI is 10.5281/zenodo.3252172

**Comment by xuanxu** [comment]
@whedon set v0.1.1 as version

**Comment by whedon** [comment]
OK. v0.1.1 is the version.

**Comment by xuanxu** [comment]
@whedon set 10.5281/zenodo.3252172 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3252172" target="_blank">10.5281/zenodo.3252172</a> is the archive.

**Comment by xuanxu** [comment]
Yay! :tada:
Everything is ready por publication. Pinging @openjournals/joss-eics for final acceptance.

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1051/0004-6361/201322068 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.3847/1538-3881/aafc33 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/787

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/787, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@xuanxu - there are 2 typos in the papers, as indicated in https://github.com/NASA-Planetary-Science/sbpy/pull/158

Once these are fixed (by merging this PR), we can finish the acceptance

**Comment by danielskatz** [comment]
@mommermi - Can you merge https://github.com/NASA-Planetary-Science/sbpy/pull/158 ?

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01426/joss.01426/10.21105.joss.01426.pdf)

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1051/0004-6361/201322068 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.3847/1538-3881/aafc33 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/788

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/788, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1142498581221388288) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/789
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01426](https://doi.org/10.21105/joss.01426)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01426/status.svg)](https://doi.org/10.21105/joss.01426)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01426">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01426/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01426/status.svg
   :target: https://doi.org/10.21105/joss.01426
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01426/status.svg)](https://doi.org/10.21105/joss.01426)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by danielskatz** [comment]
Thanks to @Juanlu001 for reviewing and @xuanxu for editing

**Comment by mommermi** [comment]
Thank you all for the quick processing of this paper!
