### ISSUE TITLE
[REVIEW]: Eyestream: An open WebSocket-based middleware for serializing and streaming eye tracker event data from Gazepoint GP3 HD research hardware

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1620]
**Submitting author:** @MLHale (<a href="http://orcid.org/0000-0002-8433-2744">Matthew Hale</a>)
**Repository:** <a href="https://github.com/MLHale/eyestream" target ="_blank">https://github.com/MLHale/eyestream</a>
**Version:** 1.1
**Editor:** @cMadan
**Reviewer:** @RingoHHuang, @adswa
**Archive:** <a href="https://doi.org/10.5281/zenodo.3549022" target="_blank">10.5281/zenodo.3549022</a>

## Status

[![status](http://joss.theoj.org/papers/fd9d05f026d1acc24d023163eba34267/status.svg)](http://joss.theoj.org/papers/fd9d05f026d1acc24d023163eba34267)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/fd9d05f026d1acc24d023163eba34267"><img src="http://joss.theoj.org/papers/fd9d05f026d1acc24d023163eba34267/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/fd9d05f026d1acc24d023163eba34267/status.svg)](http://joss.theoj.org/papers/fd9d05f026d1acc24d023163eba34267)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/MLHale/eyestream" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@RingoHHuang & @adswa, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @cMadan know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/MLHale/eyestream">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 1.1
- [x] **Authorship:** Has the submitting author (@MLHale) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/MLHale/eyestream">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 1.1
- [x] **Authorship:** Has the submitting author (@MLHale) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @RingoHHuang, @adswa it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01620/joss.01620/10.21105.joss.01620.pdf)

**Comment by cMadan** [comment]
@adswa @RingoHHuang, how are your reviews progressing? Thanks!

**Comment by adswa** [comment]
Thanks for the poke, and sorry for the delay @cMadan . I have a long train ride upcoming on sunday and plan to finish it then...

**Comment by cMadan** [comment]
@adswa, no worries, thanks for the update!

**Comment by adswa** [comment]
(My apologies - cancelled train, overcrowded replacement, no WIFI. I'll try to squeeze it in over the next two days)

**Comment by adswa** [comment]
Hey everyone, from my POV and based on what I am able to review given I don't have the hardware and OS available to test the full functionality, my review is finished.
I can confirm that the items on the checklist apply with the exception of "functionality". I have a minor issue open regarding the paper, but once this is addressed, I'd be happy to approve this submission - all with the explicit notion that I was not able to actually test the functionality. Thanks to @MLHale for providing an open source interface to make the raw data accessible, and for being so swift and diligent in replying to my issues, and thanks to everyone involved for this wonderful way of publishing and reviewing research items!

**Comment by RingoHHuang** [comment]
@cMadan - I'll find time to test the program with the Gazepoint hardware some time this week.

**Comment by MLHale** [comment]
@adswa - I have implemented your change list. Really thanks again for all of your review inputs and thoughtful contributions. I also like this collaborative process - it was been very constructive to receive and implement feedback in this way!

**Comment by cMadan** [comment]
@adswa, thanks for the update! That sounds good to me--I really appreciate your thorough efforts here.

@RingoHHuang, great, looking forward to it!

@MLHale, I'm glad to hear you're finding the review process here constructive :).

**Comment by RingoHHuang** [comment]
Hi @cMadan @MLHale @adswa,

I've just tested Eyestream using my Gazepoint 60 Hz eye-tracker and can confirm its functionality. My review of this submission is complete, and I'm ready to approve it. Thanks @MLHale for your help in addressing my many installation and testing questions, and for amending the documentation accordingly. I think Eyestream will be a valuable addition to the eye-tracking development community and will broaden the use case for Gazepoint eye-trackers. I'm excited to see future applications built off of this software. Thanks to all involved - it was a pleasure reviewing this submission!

**Comment by MLHale** [comment]
@adswa @RingoHHuang @cMadan - Thanks again for your time and effort in the review. I really appreciate all of the testing and improvements.

**Comment by MLHale** [comment]
Hi @cMadan - Is there anything else I need to do to move the review forward? Thanks!

**Comment by cMadan** [comment]
@RingoHHuang, thanks for reviewing this submission!

@MLHale, I need to do some final checks, but we're almost done! (So the review is with me now.)

**Comment by cMadan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01620/joss.01620/10.21105.joss.01620.pdf)

**Comment by cMadan** [comment]
@MLHale, it looks like the bib needs a few fixes (missing year, missing capitalisation, missing page numbers).

**Comment by MLHale** [comment]
@cMaden - I will look over that and get it fixed tonight. Thanks

**Comment by danielskatz** [comment]
👋 @MLHale - did this happen?

**Comment by MLHale** [comment]
@danielskatz @cMadan - Yes, just now - my apologies. Thanks for the reminder. I apparently had an un-pushed commit. 

Changes are pushed now on commit:
https://github.com/MLHale/eyestream/commit/7a95b7423f7ad2a4f3d1053025b890baa189f42d

**Comment by MLHale** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1620 with the following error: 

 Error reading bibliography ./paper.bib (line 20, column 3):
unexpected "y"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by MLHale** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01620/joss.01620/10.21105.joss.01620.pdf)

**Comment by cMadan** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1145/2723872.2723882 is OK
- 10.24251/HICSS.2018.108 is OK
- 10.1109/ICWS.2015.49 is OK
- 10.1109/HICSS.2015.670 is OK
- 10.1016/j.bbr.2006.07.024 is OK
- 10.1145/507079.507082 is OK
- 10.1109/TCE.2012.6227433 is OK

MISSING DOIs

- https://doi.org/10.29268/stsc.2017.5.1.1 may be missing for title: Apriori Prediction of Phishing Victimization Based on Structural Content Factors

INVALID DOIs

- None
```

**Comment by cMadan** [comment]
@MLHale, can you fix the author name for the pyOpenGaze reference so it's the person's actual name (Edwin Dalmaijer)? Also add the DOI as suggested above, as it does seem correct (http://hipore.com/stsc/contents.html#v5.n1.2017).

After that we can move on to the last stages before acceptance.

**Comment by MLHale** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1145/2723872.2723882 is OK
- 10.24251/HICSS.2018.108 is OK
- https://doi.org/10.29268/stsc.2017.5.1.1 is OK
- 10.1109/ICWS.2015.49 is OK
- 10.1109/HICSS.2015.670 is OK
- 10.1016/j.bbr.2006.07.024 is OK
- 10.1145/507079.507082 is OK
- 10.1109/TCE.2012.6227433 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by MLHale** [comment]
Hi @cMadan - Thanks for catching that! Sorry for the delay. I was away from my office for the past week or so. I made the corrections requested in the commit referenced above.

**Comment by cMadan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01620/joss.01620/10.21105.joss.01620.pdf)

**Comment by cMadan** [comment]
@MLHale, everything looks good to me!

To move forward with accepting your submission, there are a few last things to take care of:

- [ ] Make a tagged release of your software, and list the version tag of the archived version here. 
- [ ] Archive the reviewed software in Zenodo 
- [ ] Check the Zenodo deposit has the correct metadata, this includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it); you may also add the authors' ORCID.
- [ ] List the Zenodo DOI of the archived version here.

You may find this helpful: https://guides.github.com/activities/citable-code/

**Comment by MLHale** [comment]
Hi @cMadan - Thanks!

Here is the tagged release
https://github.com/MLHale/eyestream/releases/tag/1.1

**Comment by MLHale** [comment]
The Zenodo archive is available here:
10.5281/zenodo.3549022

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3549022.svg)](https://doi.org/10.5281/zenodo.3549022)

**Comment by cMadan** [comment]
@whedon set 1.1 as version

**Comment by whedon** [comment]
OK. 1.1 is the version.

**Comment by cMadan** [comment]
@whedon set 10.5281/zenodo.3549022 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3549022" target="_blank">10.5281/zenodo.3549022</a> is the archive.

**Comment by cMadan** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1145/2723872.2723882 is OK
- 10.24251/HICSS.2018.108 is OK
- https://doi.org/10.29268/stsc.2017.5.1.1 is OK
- 10.1109/ICWS.2015.49 is OK
- 10.1109/HICSS.2015.670 is OK
- 10.1016/j.bbr.2006.07.024 is OK
- 10.1145/507079.507082 is OK
- 10.1109/TCE.2012.6227433 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1111

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1111, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by cMadan** [comment]
@openjournals/joss-eics, I think we're all set to accept here!

**Comment by MLHale** [comment]
@cMadan - Thanks again for all of your help. I want to reiterate how awesome this review process has been. Seriously the most transparent, useful, and enjoyable review process I've seen. 

I really like that reviewer feedback is so collaborative, can be incorporated into the work in near real-time, and then iterated on if the fix didn't address the feedback. This kind of process makes for a better product and is (I hope) the future of academia and publishing!

I'll definitely be publishing in this venue again!

**Comment by kthyng** [comment]
Hi @MLHale I've made some tweaks to your paper.md and paper.bib to improve spacing around the references and preserve capitalization (mostly). Please merge PRs [11](https://github.com/MLHale/eyestream/pull/11) and [12](https://github.com/MLHale/eyestream/pull/12) if you please.

**Comment by MLHale** [comment]
@kthyng Thanks for these improvements. I just accepted the PRs.

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01620/joss.01620/10.21105.joss.01620.pdf)

**Comment by kthyng** [comment]
Ok looks good!

**Comment by kthyng** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1145/2723872.2723882 is OK
- 10.24251/HICSS.2018.108 is OK
- https://doi.org/10.29268/stsc.2017.5.1.1 is OK
- 10.1109/ICWS.2015.49 is OK
- 10.1109/HICSS.2015.670 is OK
- 10.1016/j.bbr.2006.07.024 is OK
- 10.1145/507079.507082 is OK
- 10.1109/TCE.2012.6227433 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1123

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1123, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1197626687267184645) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1124
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01620](https://doi.org/10.21105/joss.01620)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kthyng** [comment]
Congrats to @MLHale on your new paper! Thanks to editor @cMadan and reviewers @RingoHHuang and @adswa — we wouldn't be here without you!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01620/status.svg)](https://doi.org/10.21105/joss.01620)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01620">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01620/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01620/status.svg
   :target: https://doi.org/10.21105/joss.01620
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01620/status.svg)](https://doi.org/10.21105/joss.01620)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by MLHale** [comment]
@kthyng - Thanks!
