### ISSUE TITLE
[REVIEW]: Porpoise tracker

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1654]
**Submitting author:** @henrikmidtiby (<a href="http://orcid.org/0000-0002-3310-5680">Henrik Skov Midtiby</a>)
**Repository:** <a href="https://github.com/henrikmidtiby/PorpoiseTracker" target ="_blank">https://github.com/henrikmidtiby/PorpoiseTracker</a>
**Version:** v1.0.0
**Editor:** @kthyng
**Reviewer:** @abhishekbajpayee, @jizecn
**Archive:** Pending

## Status

[![status](https://joss.theoj.org/papers/f62c307f4a33af9233436809b4709cf3/status.svg)](https://joss.theoj.org/papers/f62c307f4a33af9233436809b4709cf3)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/f62c307f4a33af9233436809b4709cf3"><img src="https://joss.theoj.org/papers/f62c307f4a33af9233436809b4709cf3/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/f62c307f4a33af9233436809b4709cf3/status.svg)](https://joss.theoj.org/papers/f62c307f4a33af9233436809b4709cf3)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/henrikmidtiby/PorpoiseTrackerJOSSPaper/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@abhishekbajpayee & @jizecn, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @kthyng know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/henrikmidtiby/PorpoiseTracker">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@henrikmidtiby) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/henrikmidtiby/PorpoiseTracker">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@henrikmidtiby) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @abhishekbajpayee, @jizecn it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1654 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon.rb:143:in `block in check_orcids': Problem with ORCID (0000-0000-0000-0000) for Henrik Dyrberg Egemose (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon.rb:141:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon.rb:141:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon.rb:88:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by henrikmidtiby** [comment]
@kthyng Can you change the repository to https://github.com/henrikmidtiby/PorpoiseTracker ?
Right now the repository points towards a url, which only contains the paper and not the source code. If it is difficult to change, I can resubmit the paper with the correct information.

**Comment by henrikmidtiby** [comment]
> PDF failed to compile for issue #1654 with the following error:
This commit should fix the issue with the missing orcid id for Henrik Dyrberg Egemose.
https://github.com/henrikmidtiby/PorpoiseTracker/commit/c3bb5f7eec5936373d553306e56ed58eeeabdc5c

**Comment by arfon** [comment]
> @kthyng Can you change the repository to https://github.com/henrikmidtiby/PorpoiseTracker ?
> Right now the repository points towards a url, which only contains the paper and not the source code. If it is difficult to change, I can resubmit the paper with the correct information.

I've made this update.

**Comment by henrikmidtiby** [comment]
@whedon generate pdf


søn. 18. aug. 2019 kl. 19.26 skrev ooo[bot] <notifications@github.com>:

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01654/joss.01654/10.21105.joss.01654.pdf)

**Comment by henrikmidtiby** [comment]
The article proof look fine.

**Comment by jizecn** [comment]
> > @kthyng Can you change the repository to https://github.com/henrikmidtiby/PorpoiseTracker ?
> > Right now the repository points towards a url, which only contains the paper and not the source code. If it is difficult to change, I can resubmit the paper with the correct information.
> 
> I've made this update.

The embedded link in the sentence of 
_Repository: Is the source code for this software available at the repository url?_
is actually still pointing to the wrong url.

**Comment by jizecn** [comment]
Thanks for suggesting me to review the code/paper submission @henrikmidtiby 

I have done a quick read of the paper, but have not managed to proceed to test the code as instructed (due to different operating system I use (Mac OS).). 

Correct me if I am wrong, since I have not looked into the code in detail. I think the paper subject is a little misleading. Porpoise Tracker, to me, implies automatic detection and track of Porpoise or similar, where the work provides a GUI based application that allows importing Drone logs and video footages and the measure of Porpoise sizes is a manual process. The work seems to me aiming for end users of Porpoise behaviour researchers. Therefore, I suggest the authors to make the target audiences more explicit in the statement. Otherwise, you may attract computer vision scientists seeking target tracking algorithms solutions. 

The paper states that "The accuracy of method was investigated by [@Midtiby2019Havforsker]". However, I could not find the link to the reference cited. If possible, can you add a DOI or link to the reference, if it can be made publicly available online. 

Other minor remarks: 
* There is a small typo in the document, "To to that you can..." should be "To do that ...". 
* You might want to add a short description of the project on your github repo.

This is my first review for JOSS. I hope the above makes sense. Thanks.

**Comment by kthyng** [comment]
@henrikmidtiby Have you or any colleagues installed this software on a Mac? Or do you have access to one to try? Ideally, I would hope between you and @jizecn we can get this software installed on a mac, or there could be an alternative setup like a virtual machine or docker image so that @jizecn can review your submission. Expanding your installation possibilities would also improve your submission.

**Comment by henrikmidtiby** [comment]
@kthyng We attempted to install it on a mac six months ago, but it failed due to some missing requirements / dependencies. We haven't tried to install it on MacOS since. 
I will test whether the program installs in a virtual machine and report back.

**Comment by henrikmidtiby** [comment]
@kthyng I have found some unexpected issues related to graphics drivers and the oracle virtual box emulator that I have set up. This hinders the porpoise tracker to load a video and makes rest of the program useless. I am searching for a workaround.

**Comment by kthyng** [comment]
@henrikmidtiby Thanks for the updates. I'll wait to hear more.

**Comment by jizecn** [comment]
> @henrikmidtiby Have you or any colleagues installed this software on a Mac? Or do you have access to one to try? Ideally, I would hope between you and @jizecn we can get this software installed on a mac, or there could be an alternative setup like a virtual machine or docker image so that @jizecn can review your submission. Expanding your installation possibilities would also improve your submission.

I am now with Linux. Will give it a try.

**Comment by kthyng** [comment]
I'll just type a ping here for everyone. @henrikmidtiby were you able to make any progress on a workaround, or are you still in the process?

**Comment by henrikmidtiby** [comment]
@kthyng I got stuck in the workaround and was distracted due to real life events afterwards. My hope to get it to work is quite small at the moment, as the error messages that I battle with does not help me identify what is wrong with my virtual machine.

**Comment by kthyng** [comment]
Hi @abhishekbajpayee have you been able to make any progress on your review? It'd be great to see how your installation proceeds.

**Comment by abhishekbajpayee** [comment]
I tried installing. Seems like `libcairo2-dev` needs to be added to the `sudoapt install ...` list. Even after installing `libcairo2-dev`, when I run `pip install -r requirements.txt`, I see long error because of:
```
No package 'py3cairo' found
```
Also, it seems if someone installs from a fresh clean OS, `apt install python3-pip` will be needed. FYI, I am installing in a fresh `ubuntu:18.04` docker container.

@henrikmidtiby could you address some of these issues?

**Comment by henrikmidtiby** [comment]
@abhishekbajpayee I will take at look at this within a few days.

**Comment by henrikmidtiby** [comment]
@abhishekbajpayee I have pushed an updated installation guide to github.
https://github.com/henrikmidtiby/PorpoiseTracker/commit/13b76acc2c7cdbf36ab824512cd7d16c24f631db

The installation guide was tested on a minimal installation of Ubuntu 18.04.3 LTS, where the first thing I did after updating all installed packages was to install the porpoise tracker program.

**Comment by henrikmidtiby** [comment]
@abhishekbajpayee I have tried to install the porpoise tracker in a docker container, but is stuck on the following issue.

```
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
```

The approach is based on the Dockerfile shown below. Keep in mind that this is my first attempt at using docker ...
```
FROM ubuntu:18.04
LABEL maintainer="Henrik Skov Midtiby"

ENV SHELL /bin/bash

RUN apt-get update && \
    apt-get install -y python3-venv wine64 gstreamer1.0-libav gobject-introspection python3-gi python3-gi-cairo gir1.2-gtk-3.0 libgirepository1.0-dev git python-gst-1.0 ffmpeg libcairo2-dev pkg-config python3-dev


ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN mkdir -p /usr/local/src/porpoisetracker
RUN cd /usr/local/src/porpoisetracker && \
	git clone https://github.com/henrikmidtiby/PorpoiseTracker.git
RUN cd /usr/local/src/porpoisetracker/PorpoiseTracker && \
	pip install -r requirements.txt
RUN cd /usr/local/src/porpoisetracker && \
	git clone https://github.com/henrikmidtiby/gtk_modules.git
RUN cd /usr/local/src/porpoisetracker/gtk_modules && \
	pip install -e .

WORKDIR /usr/local/src/porpoisetracker
```

**Comment by danielskatz** [comment]
👋 @abhishekbajpayee - has there been any progress on this?

**Comment by kthyng** [comment]
I've been in contact by email with @abhishekbajpayee and he says he'll be working on this right away.

**Comment by kthyng** [comment]
Hi @henrikmidtiby. This review has stalled quite a bit due to the inability of the reviewers to run your code. Could you find a local colleague and/or collaborator to help you either generalize the installation process or understand the issues that the reviewers are having so they can move past them? There is a limit to the amount of effort we can reasonably ask of a reviewer in this part of the process. I propose that I pause this review in the meantime. Does this sound reasonable to you?

**Comment by abhishekbajpayee** [comment]
Here is update from my end. I tried following install instructions again and was able to get the installation working using the Dockerfile that @henrikmidtiby pasted above. But using this container, I am not able to actually run the GUI application.

Part of the issue is that I am reluctant to `sudo apt install` things on my personal machine for a review. This is why using a container is best and keeps everything isolated. So it would be ideal to have install and run instructions for a container.

@kthyng what are your thoughts on this? Let me know if my expectation is unreasonable. If that is the case, I can just modify my local environment for this review and move this forward. However, it would be difficult for me to do more reviews (which I would like to help with) if I have to modify the environment i.e. continue `sudo apt install`ing things on my personal machine every time.

**Comment by henrikmidtiby** [comment]
@kthyng I support your suggestion to pause the submission, until the installation procedure is explained in enough detail. How should I proceed from here?

I understand the reluctance by @abhishekbajpayee to install packages in the global scope.
It would be much better if we could get the docker image or something similar to work.

**Comment by kthyng** [comment]
I think we are all in agreement. I just added the "paused" label. 

@henrikmidtiby You can take the time you need to work on installation issues from your end. Then just ping here when you are ready to continue. Hopefully @abhishekbajpayee and @jizecn will be able to continue as reviewers at that time and review the submission as normal. Thanks all.

**Comment by egemose** [comment]
Hi @kthyng I have made a new submission of a rewritten version of this software to ease the installation and use, You are also the Editor at the new submission over at https://github.com/openjournals/joss-reviews/issues/2056

**Comment by kthyng** [comment]
@egemose and @henrikmidtiby — since you opened a new pre-review issue, do you want to withdraw this submission? Currently it is just paused.

**Comment by henrikmidtiby** [comment]
@kthyng We would like to withdraw this submission. The new submission #2056 is meant to replace this submission.

**Comment by kthyng** [comment]
@whedon withdraw

**Comment by whedon** [comment]
Paper withdrawn.
