### ISSUE TITLE
[PRE REVIEW]: IPART: A Python Package for Image-Processing based Atmospheric River Tracking

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2197]
**Submitting author:** @Xunius (<a href="http://orcid.org/0000-0001-5877-5608">Guangzhi XU</a>)
**Repository:** <a href="https://github.com/ihesp/IPART" target ="_blank">https://github.com/ihesp/IPART</a>
**Version:** v1.0
**Editor:** @kbarnhart
**Reviewers:** @sadielbartholomew, @rabernat
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @Xunius. **Currently, there isn't an JOSS editor assigned** to your paper.

@Xunius if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by kthyng** [comment]
Hi @Xunius! I have updated the repo address to https://github.com/ihesp/AR_tracker — let me know if this is incorrect.

**Comment by kthyng** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.17 s (229.6 files/s, 63563.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          16           1491           1837           3341
reStructuredText                14            520            174           1164
TeX                              1             48              0            587
Jupyter Notebook                 5              0           1260            339
Markdown                         2             62              0            194
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            40           2133           3279           5660
-------------------------------------------------------------------------------


Statistical information for the repository '2197' was gathered on 2020/05/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
guangzhi                        14          6835            166          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
guangzhi                   6669           97.6          0.0                8.68
```

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2197 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/2197/joss/paper.md): found a tab character that violate intendation while scanning a plain scalar at line 9 column 11 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon.rb:125:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon.rb:85:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by kthyng** [comment]
@openjournals/dev Is there a reference for finding what characters are not allowed in the papers? It looks like that is the problem. Is & ok?

**Comment by kthyng** [comment]
@Xunius I am conflicted on this paper so I will find another editor.

**Comment by kthyng** [comment]
@kbarnhart I know I just asked you about another submission, but we plan not to assign over 3 total at the moment. Are you able to edit this submission too? I am a good fit but I am conflicted.

**Comment by kbarnhart** [comment]
@kthyng I can handle this too.

**Comment by kbarnhart** [comment]
@whedon assign @kbarnhart as editor

**Comment by danielskatz** [comment]
> @openjournals/dev Is there a reference for finding what characters are not allowed in the papers? It looks like that is the problem. Is & ok?

This is not an issue with the paper body, but with the header.
Specifically, on line 9
	orcid: 0000-0001-5877-5608
should be 
    orcid: 0000-0001-5877-5608

(basically, a tab needs to be replaced with 4 spaces)

**Comment by Xunius** [comment]
Thanks. Just made a quick fix: https://github.com/ihesp/AR_tracker/commit/6e617d8f0d5ad43beec1dbbf8ea693f4e57013cf

**Comment by kbarnhart** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02197/joss.02197/10.21105.joss.02197.pdf)

**Comment by Xunius** [comment]
@kbarnhart I noticed that generated PDF is using this format of citation `[@authoryear]` with no reference list in the end. In the PDF I compiled myself (using the preview tool or a Llinux commandline utility, I can't remember which exactly) the citations look correct. Is it something again related to formatting errors?

**Comment by Xunius** [comment]
@kbarnhart Thanks. I think I must have accidentally reverted to a previous commit or something, I remembered myself fixing these citation issues before. Anyway, I just pushed a new commit fixing this, and tried the online preview service again. Now it compiles correctly.

**Comment by Xunius** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02197/joss.02197/10.21105.joss.02197.pdf)

**Comment by Xunius** [comment]
Looking good now.

**Comment by kbarnhart** [comment]
@Xunius

Thank you for submitting this contribution to JOSS. As part of the review process, one of the JOSS editors (me) does an initial screening to ensure the submission is in scope and identify if there are any issues that should be addressed before the review process starts. I am very excited to see this contribution reviewed at JOSS, but based on examining the contents of the submission and discussing with the JOSS editorial board, there are a number of things that I think should be addressed before the submission proceeds to review. I've outlined these issues below in a checklist. 

As always, please do not hesitate to ask questions or raise concerns. You may contact me here on this issue thread or at krbarnhart@usgs.gov

The typical procedure at JOSS at this point is to label the submission as "paused" while you address these issues. When you are done, you would notify me and I will resume the submission. 

- [ ] _Installation instructions:_ The contribution is a set of scripts without formal packaging. Formal packaging is not required, but some instructions for how a user might use this package outside of the source directory is merited. In addition, I might consider making a conda-environment specification. 
- [ ] _Example Usage:_ The set of notebooks you have created provide nice examples but they appear to rely on data from a Google Drive. I would recommend either providing the example data as part of the package or pointing to an existing reanalysis archive. 
- [ ] _API documentation:_ While it looks like everything that is exposed in a function signature is documented, examining the code itself reveals that there are quite a few local and global variables that are hard coded into the scripts. These include paths to files and the contents of `PARAM_DICT`. I would recommend that these parameters exposed as user specified without the need to edit the source code (e.g., as function keyword arguments). 
- [ ] _Tests:_ It appears that tests exist but there are no instructions for running them. 
- [ ] _Atmospheric river algorithm context:_ Could you place your algorithm more clearly in the context of the [ARTMIP effort](http://www.cgd.ucar.edu/projects/artmip/) (Rutz et al., 2019; Shields et al., 2018) and the algorithms considered by that group. 

_References_
Rutz, J. J., Shields, C. A., Lora, J. M., Payne, A. E., Guan, B., Ullrich, P., et al. ( 2019). The atmospheric river tracking method intercomparison project (ARTMIP): quantifying uncertainties in atmospheric river climatology. Journal of Geophysical Research: Atmospheres, 2019; 124: 13777– 13802. https://doi.org/10.1029/2019JD030936

Shields, C. A., Rutz, J. J., Leung, L.-Y., Ralph, F. M., Wehner, M., Kawzenuk, B., Lora, J. M., McClenny, E., Osborne, T., Payne, A. E., Ullrich, P., Gershunov, A., Goldenson, N., Guan, B., Qian, Y., Ramos, A. M., Sarangi, C., Sellars, S., Gorodetskaya, I., Kashinath, K., Kurlin, V., Mahoney, K., Muszynski, G., Pierce, R., Subramanian, A. C., Tome, R., Waliser, D., Walton, D., Wick, G., Wilson, A., Lavers, D., Prabhat, Collow, A., Krishnan, H., Magnusdottir, G., and Nguyen, P.: Atmospheric River Tracking Method Intercomparison Project (ARTMIP): project goals and experimental design, Geosci. Model Dev., 11, 2455–2474, https://doi.org/10.5194/gmd-11-2455-2018, 2018.

**Comment by kbarnhart** [comment]
@Xunius I wanted to follow up and see if you had any questions about my comments.

**Comment by Xunius** [comment]
@kbarnhart Thanks for the comments.
I'm not quite used to packaging the code as nicely as a professional programmer, because 99% of the time the only user of the code I wrote is myself, so there is no surprise there is a lot of rough edges.

I got a few questions:
1. I can't promise making a conda-environment specification will work, I'll have to try. My experience with the `cdat` package is that it can be annoying to install (and I'm blaming other science programmers for not packaging the code well).
2. I'm still not sure the best way to provide the sample data. The computation requires at least a few hundred MB of data, I doubt the user would like to clone a repo with this big of binary data in it. On the other hand, many reanalysis data centers require a sign-up to download, and the user has to select the data domain in the web interface to download. So a link to the data archive alone probably is not sufficient. I would also need to give some instructions on the selection of the required domain?
3. on the "instructions for running them" part, is `python -m unittest test/test_something.py` the correct type of instruction? Again I'm not used to write tests.

**Comment by kbarnhart** [comment]
Thanks for those questions @Xunius I'll do my best to provide some answers. I would also recommend looking at some of repositories of [other papers](https://joss.theoj.org/) published in JOSS to see some existing examples of providing installation and testing instructions, as well as approaches to documentation and packaging code. I often find looking at these examples to be helpful.

- Just to be clear, I'm not recommending that you need to distribute your code through conda-forge or pypi, just to create a `environment.yml` specification so that the required environment is described by that file and a user might install it with something like the following ([conda environment documentation](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file)):

```bash
conda env create -f environment.yml
```

- The reason I recommend this is that one of the things that happens during the JOSS review process is that reviewers will test installation instructions. While it is not a requirement, using Continuous Integration platforms like Appveyor and Travis is one way to check that your installation instructions and tests work on multiple platforms and multiple python versions. 

- Regarding sample data: I agree that the sample data should not be present in this repository. You make a good point regarding many re-analysis data centers requiring a log in. I will discuss with the JOSS editorial board and see if we can make a recommendation for how to best handle this.

- Regarding instructions for testing: I would recommend a sentence that describes what the existing tests do and a statement about how a user might run the all the tests. There are a number of ways you could do this (with unittest only, or with additional testing packages such as nosetest or pytest). The important thing is that you indicate to a user how to assess whether they have installed the package correctly and the what the tests passing means. 

As always, please reach out with questions and for clarification.

**Comment by kbarnhart** [comment]
@Xunius I wanted to follow up with some recommendations regarding the sample data based on discussing this with the rest of the JOSS editorial team. 

We would recommend that you place the sample data in a public archive (e.g., zenodo, figshare) and then provide instructions for users to obtain the data (e.g., use wget/curl in the notebook). 

I would also recommend indicating a link to the data archive (e.g., on whichever reanalysis server you are using) and a brief statement of what the data domain you have selected is. 

Please let me know if I can provide any clarification on this recommendation.

**Comment by Xunius** [comment]
@kbarnhart Thanks for the recommendation. 

We have made some changes to the submission:

1. We are changing to the title to "IPART: A Python Package for Image-Processing based Atmospheric River Tracking". The github repo name is also changed to https://github.com/ihesp/IPART (I noticed that clicking the old URL at the top of this issue/thread points to the updated repo though).
2. The package is now install-able via conda: `conda install -c guangzhi ipart`. I've uploaded a py2 and a py3 version to anaconda cloud, and tested both on my own machine. The relevant installation instructions are also updated accordingly in the README.md and the readthedocs page.
3. Code has been re-structured so that the core functions are put in the `ipart` module, and a few example scripts are given in the `scripts` folder, mainly as templates for users to modify and build their own working scripts.
4. Notebooks have been updated using the new module design.
5. I've managed to squeeze the sample data to a much smaller size (~10 MB each, ~20 MB total), and I think that's acceptable size to put in the repo itself. So they are now saved in the `notebooks` folder. Metadata of these sample data are given in the relevant notebook.
6. The readthedocs pages are updated.
7. One requirement file is created for py2 version and another for py3 version.
8. Some minor changes to the tests, and in the README.md, added the instruction to run the tests: `python -m unittest discover -s tests`.

Please let me know whether these changes sufficiently address the previous issues.

**Comment by kbarnhart** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02197/joss.02197/10.21105.joss.02197.pdf)

**Comment by Xunius** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02197/joss.02197/10.21105.joss.02197.pdf)

**Comment by Xunius** [comment]
@kbarnhart PDF looks good now.

**Comment by kbarnhart** [comment]
@Xunius thank you for your update. Unfortunately, I don't think your changes sufficiently address the issues I pointed out in the checklist above. Based on the changes you've made I notice two additional concerns. 

- [ ] I am concerned by your use of conda-forge to provide the package,  without using conda to mange the dependencies. Please correct me if I am wrong, but it appears that your conda binary doesn't manage the dependencies. JOSS intends to be flexible regarding the specifics of software installation in order to respect the differences between submissions and the needs of the developers, but use of a package manager _implies_ that the package manager is managing dependencies. I would recommend that you do either (a), or (a) and (b) of the following: 

    a) Provide a conda [environment .yml](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file) file with instructions to use it to create the environment. After creating and activating the environment, a user would then be instructed to run something like `python setup.py` or `pip install -e .` to install the package from source. Thus installation instructions could be something similar to the following:

    ```bash
    git clone https://github.com/ihesp/IPART.git
    cd ipart
    conda env create -f environment.yml
    python setup.py install
    ```

    b) If you want to distribute a binary through a package manager (which is certainly encouraged but not is not required), please ensure that installation by this method manages the dependencies. 

- [ ] It does not appear to me that you have described how your algorithm compares with those presented in the two ARTMIP papers. I see the addition of the two references, but no discussion of algorithms. 

I want to follow up regarding the comment I made above about hard coded paths and the `PARAM_DICT` argument. I made this comment because one of the [submission requirements for JOSS](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) is that a submission must be _"feature-complete (no half-baked solutions) and designed for maintainable extension (not one-off modifications)"_. The presence of hard coded paths and a large number of input parameters that are not documented as part of the API indicated to me that the package has not yet reached a state where it is designed for maintainable extension. I think that your change to distinguish between the `ipart` module and the set of example scripts is a good first step. 

One of the goals of JOSS is to improve software through the review process, so I provided the above feedback in support of improving this submission so it can meet this criteria and move forward into review. 

I look forward to seeing this submission meet these minimum requirements and move forward to review. However, at present, it is not yet there. 

Please let me know if you have any questions or clarifications. I will do my best to answer them.

**Comment by kbarnhart** [comment]
@openjournals/joss-eics could you please update the repository address and title of this submission? I don't think I have privileges to do this.

Title: "IPART: A Python Package for Image-Processing based Atmospheric River Tracking"
Repo: https://github.com/ihesp/IPART

**Comment by Xunius** [comment]
@kbarnhart 
Based on your comments I have made some further changes:
1. added 2 environment files and instructions for creating the conda envs with them.
2. things in `PARAM_DICT` are now function keyword arguments, function calls are changed to `func(..., **PARAM_DICT)`. The dict name being spelled using capitals does not make it "hard coded", and I wonder how much of a difference this makes.
3. I also doubt that JOSS is the suitable platform for discussing methodological inter-comparisons like what ARTMIP is doing. I've added 2 sentences describing the comparisons we have made. The work was submitted to a separate journal, and is still in production atm, so I can't give a reference just yet.

**Comment by kbarnhart** [comment]
@Xunius thank you for making those changes. 

1. I see that you have created new environment files, however, your changes have not addressed my concern regarding use of a package manager but not managing dependencies. Specifically, your environment.yml files still point to the conda-forge distribution of IPART that does not manage the dependencies. 

    I will re-state what I said in the prior comment, that use of a package manager is encouraged, but not required, and if a package manager is used, it should handle the dependencies. 

    I also note that your conda environment files appear to be an un-edited export from `conda env export` such that every package installed in your environment is listed and your computer's prefix is listed. I recommend that you use `conda env export --from-history` as described [here](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#exporting-an-environment-file-across-platforms) and edit the .yml file so that one might expect it would work on another person's computer (for example, make sure to remove the prefix section of the yaml). The environment.yml only needs to list the direct dependencies of IPART.

2. Thank you for revising the function signature so that the parameters that control AR detection are documented. You have now sufficiently addressed this issue. 

    A related clarification: When I mentioned "hard coded" I was referring to the hard coded paths to files on your file system in your example scripts (for example, [here](https://github.com/ihesp/IPART/blob/master/scripts/detect_ARs.py#L99), not to the `PARAM_DICT`. 

    The issue with the `PARAM_DICT` (that you have now addressed) is that the parameters that control AR detection were not described or documented in the API documentation. Describing these parameters in the API documentation _does make a difference_.

3. Regarding comparison to ARTMIP, perhaps I have not been clear in my recommendation. I agree that JOSS is not a suitable platform for methodological inter-comparisons. When I wrote _"Could you place your algorithm more clearly in the context of the ARTMIP effort (Rutz et al., 2019; Shields et al., 2018) and the algorithms considered by that group."_ I was trying to encourage you to describe how your method fits into the classification of AR algorithms used by the ARTMIP project. For example, Ruiz et al. (2019) Table 1 and Figure 5 classify the AR algorithms on a number of different bases (e.g., type, geometry requirements, threshold requirements,  absolute/relative, global/regional). As best as I can tell, your contribution is a relative threshold method, by their classification. But this is just one aspect of the classification. Two new sentences that place your algorithm in the context of their classification scheme would be more than sufficient. 

Please let me know if you have questions or clarifications about my comments. I look forward to hearing from you that these issues have been addressed so that this submission can move forward into review.

**Comment by Xunius** [comment]
@kbarnhart please checkout the new changes:
1. the environment files are re-created using `--from-history` flag, and without the `prefix`. It only includes direct dependencies. 
2. Minor edits in `paper.md`.

**Comment by kbarnhart** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02197/joss.02197/10.21105.joss.02197.pdf)

**Comment by kbarnhart** [comment]
@Xunius Thank you for updating me to these changes. I think the added text related to ARTMIP substantially improves the paper. 

Regarding the installation, your Option 1 does not actually install IPART. This linked pull request makes some recommended changes to your setup.py file and readme.md. ihesp/IPART/pull/1

Regarding your installation Options 2 and 3 (which I have removed in the PR), I note that you have ignored the statement I made twice in prior comments that it is not appropriate to use conda to install a package without also using it to also manage that packages dependencies. This issue must be addressed before this submission can move forward into review. One way to address it would be to delete the files on anaconda.org and to merge my PR. You, of course, may address it however you see fit. 

You might wonder why I have continued to comment on the installation instructions. The reason is as follows: It is very important that papers submitted to JOSS have installation instructions that reviewers can be expected to follow. One of the first items in the JOSS review checklist is:

**Installation:** Does installation proceed as outlined in the documentation?

It is for this reason that, as a topical editor, I carefully check the installation instructions during the pre-review process.

Please let me know if you have questions or clarifications about my comments. I look forward to hearing from you that this issue has been addressed so that this submission can move forward into review.

**Comment by Xunius** [comment]
@kbarnhart Thanks. The PR has been merged.
The conda package came with dependencies in my previous fix, except that for py3, the cdms2 and cdutil dependencies don't work out of the box ([one related issue I'm having](https://github.com/CDAT/cdat/issues/2252#issuecomment-644428720)), that's why I added manual install instructions if that one doesn't work. For py2 it works as expected, installing `ipart` from conda pulls in the dependencies.

As for the previous option 1, are you sure that didn't install IPART? It works on my machine without doing `python setup` or `pip install`. Anything to do with conda version? I'm using 4.8.2.

**Comment by kbarnhart** [comment]
@Xunius you can import a python module _when you are in the code's directory_ without running setup.py develop. That is why option 1 appeared to have installed ipart. If you are in another directory, however, it won't import. 

Regarding conda forge: Just in case I'm not being clear enough, what I mean by _manage all dependencies_ is that one might expect the following to install ipart and all of its dependencies:
```
$ conda create --name ipart
$ conda activate ipart
$ conda install -c guangzhi ipart
```
such that the following would work
```
$ python 
>>> import ipart
```

I find the following: 

**Ubuntu 18.04**
```
$ conda create -n ipart
$ conda activate ipart
$ conda install -c guangzhi ipart

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

**OSX**
```
$ conda create -n ipart
$ conda activate ipart
$ conda install -c guangzhi ipart
$ python
Python 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:33:30)
[Clang 9.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> ipart
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'ipart' is not defined
>>> import ipart
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/barnhark/opt/anaconda3/envs/ipart/lib/python3.7/site-packages/ipart-2.0-py3.7.egg/ipart/__init__.py", line 1, in <module>
  File "/Users/barnhark/opt/anaconda3/envs/ipart/lib/python3.7/site-packages/ipart-2.0-py3.7.egg/ipart/AR_detector.py", line 8, in <module>
ModuleNotFoundError: No module named 'numpy'
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
>>>
```
The conda installation fails on ubuntu (where I was able to successfully install using the revised Option 1), appears to succeed on Mac, but when one tries to import ipart, I find that the dependencies have not been managed (as the dependency numpy has not been installed).

I recognize that you indicated in that "the conda package came with dependencies in my previous fix". Would you have expected my above installation to work?

While we wrap up addressing this installation issue, could you also provide the GitHub handles of  reviewers you think would be appropriate for this submission? Please mention their GitHub handles without the @ (you would refer to me as kbarnhart) so they don't get unnecessary emails.

**Comment by Xunius** [comment]
@kbarnhart I'm able to create and install `ipart` all in one line, but only in py2. Doing this in separate steps seems much harder. For py3 it the conda install doesn't work. I'll have to look into that later.

For suggested reviews, perhaps:
- ajdawson
- doutriaux1
- jwblin

**Comment by kbarnhart** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02197/joss.02197/10.21105.joss.02197.pdf)

**Comment by Xunius** [comment]
@kbarnhart PDF good.

**Comment by kbarnhart** [comment]
:wave: @ajdawson @doutriaux1 @jwblin @muszyna25 would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This submission is "IPART: A Python Package for Image-Processing based Atmospheric River Tracking" by Guangzhi Xu, Xiaohui Ma and Ping Chang

This is a pre-review issue which is used to find reviewers. Once 2-3 reviewers have been found I'll start the review on a dedicated GitHub issue. At present we are asking reviewers to complete reviews in 6 weeks. If you are not able to review and have someone to recommend, please mention them here (when mentioning, please place a space after the @ of a github handle, for example, you would refer to me as "@ kbarnhart").

If you are interested in reviewing, I would recommend looking over the journal's [conflict of interest policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html?highlight=conflict%20of%20interest#joss-conflict-of-interest-policy) before the review process starts.

If you have any questions about the JOSS review process, please do not hesitate to reach out to me on this issue or at krbarnhart@usgs.gov

**Comment by muszyna25** [comment]
Hi Katy,

Thank you for your invitation to review the submission for JOSS. However, I am not able to review it, but I can recommend somebody that may be interested: @ burlen @ taobrienlbl

Thanks,
Grzegorz

**Comment by taobrienlbl** [comment]
Unfortunately I am unable to review as well, due to a conflict of interest with one of the authors.

**Comment by kbarnhart** [comment]
@muszyna25 thanks for the response and for recommending other reviewers. @taobrienlbl thanks also for your response.

**Comment by kbarnhart** [comment]
👋 @ajdawson @doutriaux1 @jwblin @burlen you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This submission is "IPART: A Python Package for Image-Processing based Atmospheric River Tracking" by Guangzhi Xu, Xiaohui Ma and Ping Chang

This is a pre-review issue which is used to find reviewers. Once 2-3 reviewers have been found I'll start the review on a dedicated GitHub issue. At present we are asking reviewers to complete reviews in 6 weeks. If you are not able to review and have someone to recommend, please mention them here (when mentioning, please place a space after the @ of a github handle, for example, you would refer to me as "@ kbarnhart").

If you are interested in reviewing, I would recommend looking over the journal's conflict of interest policy before the review process starts.

If you have any questions about the JOSS review process, please do not hesitate to reach out to me on this issue or at krbarnhart@usgs.gov

**Comment by kbarnhart** [comment]
👋 @andreas-h @rabernat @sadielbartholomew would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This submission is "IPART: A Python Package for Image-Processing based Atmospheric River Tracking" by Guangzhi Xu, Xiaohui Ma and Ping Chang

This is a pre-review issue which is used to find reviewers. Once 2-3 reviewers have been found I'll start the review on a dedicated GitHub issue. At present we are asking reviewers to complete reviews in 6 weeks. If you are not able to review and have someone to recommend, please mention them here (when mentioning, please place a space after the @ of a github handle, for example, you would refer to me as "@ kbarnhart").

If you are interested in reviewing, I would recommend looking over the journal's [conflict of interest policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html?highlight=conflict%20of%20interest#joss-conflict-of-interest-policy) before the review process starts.

If you have any questions about the JOSS review process, please do not hesitate to reach out to me on this issue or at krbarnhart@usgs.gov

**Comment by sadielbartholomew** [comment]
Hi Katy, thank you for offering a review. Yes, I am happy & able to review this submission & do so at least within 6 weeks. I have read the COI Policy & do not have any COI for this submission.

One question to confirm, though, as I have not reviewed for JOSS before: I assume it does not preclude me from being a reviewer overall if I am due to soon be a co-author on a submission to JOSS (completely unrelated to this submission)? It's okay for reviewers also to submit to JOSS generally? Thanks.

**Comment by kbarnhart** [comment]
@sadielbartholomew thank you for being willing to review this submission! I can confirm that soon-to-be submitting to JOSS does not preclude you from being a reviewer. 

I'll add you to the submission as a reviewer. I hope to start the official review thread in the next few days. 

Thanks again for participating in the JOSS review process.

**Comment by kbarnhart** [comment]
@whedon add @sadielbartholomew as reviewer

**Comment by whedon** [comment]
OK, @sadielbartholomew is now a reviewer

**Comment by kbarnhart** [comment]
👋 @andreas-h and @rabernat a quick ping to consider reviewing this submission to JOSS.

**Comment by rabernat** [comment]
Yes, I will provide a review within 6 weeks.

**Comment by kbarnhart** [comment]
Thanks for being willing to review @rabernat !

**Comment by kbarnhart** [comment]
@whedon add @rabernat as reviewer

**Comment by whedon** [comment]
OK, @rabernat is now a reviewer

**Comment by kbarnhart** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2407.
