### ISSUE TITLE
[REVIEW]: Thing Directory: Simple and lightweight registry of IoT device metadata

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3075]
**Submitting author:** @farshidtz (<a href="http://orcid.org/0000-0002-5415-9899">Farshid Tavakolizadeh</a>)
**Repository:** <a href="https://github.com/linksmart/thing-directory" target ="_blank">https://github.com/linksmart/thing-directory</a>
**Version:** v1.0.0-beta.21
**Editor:** @gkthiruvathukal
**Reviewer:** @yadudoc, @sarathsp06
**Archive:** <a href="https://doi.org/10.5281/zenodo.4616483" target="_blank">10.5281/zenodo.4616483</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/82142322bbc7aa9ce9a08ff45f67625e/status.svg)](https://joss.theoj.org/papers/82142322bbc7aa9ce9a08ff45f67625e)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/82142322bbc7aa9ce9a08ff45f67625e"><img src="https://joss.theoj.org/papers/82142322bbc7aa9ce9a08ff45f67625e/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/82142322bbc7aa9ce9a08ff45f67625e/status.svg)](https://joss.theoj.org/papers/82142322bbc7aa9ce9a08ff45f67625e)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/linksmart/thing-directory" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@yadudoc & @sarathsp06, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @gkthiruvathukal know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/linksmart/thing-directory">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@farshidtz) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/linksmart/thing-directory">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@farshidtz) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @yadudoc, @sarathsp06 it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=3.22 s (271.6 files/s, 83228.1 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
Go                              762          26210          23733         206358
Markdown                         30           1053              0           3335
Assembly                         43            449            812           2203
JSON                              3              0              0           1122
YAML                             26             97             53            979
Bourne Shell                      2             70            325            548
HTML                              2             29              0            120
TeX                               1              0              0             85
Bourne Again Shell                2             12              6             72
make                              1             11              0             33
C                                 1              8              7             24
Dockerfile                        1             10              2             22
--------------------------------------------------------------------------------
SUM:                            874          27949          24938         214901
--------------------------------------------------------------------------------


Statistical information for the repository '314e770d47ec2dc29f3a86ba' was
gathered on 2021/03/02.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Farshid Tavakolizade             3           116             77          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Farshid Tavakolizade         39           33.6          0.0               17.95
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03075/joss.03075/10.21105.joss.03075.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03075/joss.03075/10.21105.joss.03075.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/CCNC.2019.8651786 is OK
- 10.1145/2991561.2991570 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by sarathsp06** [comment]
@farshidtz had a brief look at the article proof and repository
well done! Liked the clear and concise documentation within the code.  

I had some minor concerns 
* There are some dead code 
       * eg: [`enumValues_DataSchemaType` ](https://github.com/linksmart/thing-directory/blob/42b5f6f97c6fb63c89760a01160b89713f6c040b/wot/thing_description.go#L466)
   
* There are some semantic issues like having the same JSON struct tags for multiple fields in a struct
       * eg: [wot.Link](https://github.com/linksmart/thing-directory/blob/42b5f6f97c6fb63c89760a01160b89713f6c040b/wot/thing_description.go#L202)
* There are quite a few naming convention violations `enumValues_DataSchemaType` is an example and camel cased file names are also not encouraged
* [main.registerDNSSDService](https://github.com/linksmart/thing-directory/blob/42b5f6f97c6fb63c89760a01160b89713f6c040b/discovery.go#L19) does not seem to do what was expected as line 21 instance assignment is ineffective. ie,  `.` in  `conf.DNSSD.Publish.Instance` in effect is not replaces
* there are some instances of err checks missing 
* could you please (optionally )  add a how to use section in README

**Comment by farshidtz** [comment]
> @farshidtz had a brief look at the article proof and repository
> well done! Liked the clean code and clear and concise documentation within the code.
> 
> I had some minor concerns

Thank you very much for your review, @sarathsp06.
I've addressed your concerns. Please find the responses inline:

> * There are some dead code
>   * eg: [`enumValues_DataSchemaType` ](https://github.com/linksmart/thing-directory/blob/42b5f6f97c6fb63c89760a01160b89713f6c040b/wot/thing_description.go#L466)

This is not used by this software, but others who import the package may use it to check if the value of [DataSchema.DataType](https://github.com/linksmart/thing-directory/blob/4a5dd20b04039a9b7253a794813e7a72c70d8d33/wot/thing_description.go#L276) is one of the allowed ones. I've [added comments and moved this part of the code to a better place](https://github.com/linksmart/thing-directory/commit/1a419f199bd536fa697edbc9cb256f6f446c8033) to clarify that. 

> * There are some semantic issues like having the same JSON struct tags for multiple fields in a struct
>   * eg: [wot.Link](https://github.com/linksmart/thing-directory/commit/41f19ee32f62716c1bb8b5f24da88cf4b35af358)

I found and [fixed two](https://github.com/linksmart/thing-directory/commit/75afd93fe1d9e74dd72709fdcbe421706559b03f). There are others reported by linting programs, but those are caused by the class relationship coming from WoT Thing Description. I also want to point out that the structs in this file are generated from [this JSON Schema](https://www.w3.org/TR/wot-thing-description/#json-schema-for-validation) and then modified and commented (the JSON Schema is also available [locally](https://github.com/linksmart/thing-directory/blob/4a5dd20b04039a9b7253a794813e7a72c70d8d33/wot/wot_td_schema.json)). Some strange relationships and names come from the generator. 

> * There are quite a few naming convention violations `enumValues_DataSchemaType` is an example and camel cased file names are also not encouraged

Fixed [enumValues_DataSchemaType](https://github.com/linksmart/thing-directory/blob/844c55ca311370978a684df815b6f714935b87f4/wot/thing_description.go#L295) the and [TTL](https://github.com/linksmart/thing-directory/commit/844c55ca311370978a684df815b6f714935b87f4) names to match the convention. As mentioned above, the generator of [thing_description.go](https://github.com/linksmart/thing-directory/blob/844c55ca311370978a684df815b6f714935b87f4/wot/thing_description.go) has made some decisions which are not perfect. We correct those whenever we notice any.


> * [main.registerDNSSDService](https://github.com/linksmart/thing-directory/blob/42b5f6f97c6fb63c89760a01160b89713f6c040b/discovery.go#L19) does not seem to do what was expected as line 21 instance assignment is ineffective. ie,  `.` in  `conf.DNSSD.Publish.Instance` in effect is not replaces

The function registers a DNS-SD service as its name suggests. To do so, it has to replace special characters that may come from user configurations. The function does not intend to change the source configuration. I understand the confusion because the config is passed as pointer, but this is solely to avoid copying the object. We'll consider changing it to pass by value.

> * there are some instances of err checks missing

[Added the missing error handling](https://github.com/linksmart/thing-directory/commit/a3968d9e0532d63493eb43628fb3249adc987d8a) for every function call that the linting software could detect.

> * could you please (optionally )  add a how to use section in README

I [improved the getting started section](https://github.com/linksmart/thing-directory/commit/4a5dd20b04039a9b7253a794813e7a72c70d8d33). Does this cover what you expect? 


Thanks again for you feedback, it really helps us to improve the project.

**Comment by sarathsp06** [comment]
Thank you , I think the following was not clear # probably in my explanation


main.registerDNSSDService:  does not seem to do what was expected as line 21 instance assignment is ineffective. ie, . in conf.DNSSD.Publish.Instance in effect is not replaces


The first replace is ignored as the following line is over writing the same variable

**Comment by farshidtz** [comment]
> Thank you , I think the following was not clear # probably in my explanation
> 
> main.registerDNSSDService: does not seem to do what was expected as line 21 instance assignment is ineffective. ie, . in conf.DNSSD.Publish.Instance in effect is not replaces
> 
> The first replace is ignored as the following line is over writing the same variable

Right, good catch. [Fixed it and added unit tests](https://github.com/linksmart/thing-directory/commit/b469a462704b7c602f1221088ff8d750d72ee418).

**Comment by yadudoc** [comment]
Hi @farshidtz, I've looked over the paper, documentation and poked around with a local deployment as well as the swagger UI, and overall I'm very pleased. I'd also echo @sarathsp06's comment that the code documentation is remarkable!

Here are the couple of items that I've raised as issues in the repo:
- [ ] Citation to a more recent survey paper (https://github.com/linksmart/thing-directory/issues/39)
- [ ] Access control for demo. This is mostly so that I could test out the features that require write access. (https://github.com/linksmart/thing-directory/issues/40)
- [X] Fleshing out the contributing guide (https://github.com/linksmart/thing-directory/issues/37)

**Comment by yadudoc** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03075/joss.03075/10.21105.joss.03075.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03075/joss.03075/10.21105.joss.03075.pdf) :page_facing_up: :point_left:

**Comment by yadudoc** [comment]
Following the discussion over [here](https://github.com/linksmart/thing-directory/issues/40), @farshidtz provided the keys for write access to the demo instance of the thing-directory. I've tested the advertised functionality using the [swagger UI](https://linksmart.github.io/swagger-ui/dist/?url=https://demo.linksmart.eu/thing-directory/openapi-spec-proxy/thing-directory/) and can confirm that everything seems to be in good order. In addition, all of my concerns raised above have been addressed.

@gkthiruvathukal, At this point, I would recommend accepting this paper.

**Comment by whedon** [comment]
:wave: @sarathsp06, please update us on how your review is going (this is an automated reminder).

**Comment by sarathsp06** [comment]
@gkthiruvathukal, I would recommend accepting this paper.


@farshidtz had addressed all the concerns I have raised and the project seems to be in good shape

**Comment by gkthiruvathukal** [comment]
@sarathsp06 and @farshidtz, great, I am happy to move forward with acceptance.

@farshidtz can you do the following?

Please do the following:

- [ ] Make a tagged release of your software, and list the version tag of the archived version here. 
- [ ] Archive the reviewed software in Zenodo 
- [ ] Check the Zenodo deposit has the correct metadata, this includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it); you may also add the authors' ORCID.
- [ ] List the Zenodo DOI of the archived version here.

Then I can proceed with the final steps!

**Comment by farshidtz** [comment]
Thanks a lot to @yadudoc and @sarathsp06 for their thorough feedback. 

@gkthiruvathukal, we have made the release and uploaded the archive to Zenodo. Please find the details below:

Version: v1.0.0-beta.21
DOI: https://doi.org/10.5281/zenodo.4616483

**Comment by farshidtz** [comment]
@gkthiruvathukal Do you require anything else from us? Or the final steps are in progress?

Thanks

**Comment by gkthiruvathukal** [comment]
@farshidtz I will work on the final steps. Thank you for your patience!

**Comment by gkthiruvathukal** [comment]
@whedon set v1.0.0-beta.21 as version

**Comment by whedon** [comment]
OK. v1.0.0-beta.21 is the version.

**Comment by gkthiruvathukal** [comment]
@whedon set 10.5281/zenodo.4616483 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4616483" target="_blank">10.5281/zenodo.4616483</a> is the archive.

**Comment by gkthiruvathukal** [comment]
@farshidtz I think we are good to go!  About to accept.

@yadudoc and @sarathsp06, thank you for your help in reviewing this submission.

**Comment by gkthiruvathukal** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2226

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2226, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/CCNC.2019.8651786 is OK
- 10.1145/2991561.2991570 is OK
- 10.1016/j.iot.2020.100293 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
Hi @farshidtz, I am the AEIC on duty this week doing final checks before accepting. I noticed that one reference (Schaaf 2016, for the FROST server) seems to have an issue with the author names. I think if you change the `author` field in the `.bib` file to `{Hylke {van der Schaaf} and Michael Jacoby}` or `{van der Schaaf, Hylke and Jacoby, Michael}` then bibtex should parse it correctly.

**Comment by farshidtz** [comment]
Thanks @kyleniemeyer. I have changed it and the produced [artifact](https://github.com/linksmart/thing-directory/suites/2496106542/artifacts/53883249) shows the name correctly now.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03075/joss.03075/10.21105.joss.03075.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03075/joss.03075/10.21105.joss.03075.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1382387097886203904) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2229
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03075](https://doi.org/10.21105/joss.03075)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congratulations @farshidtz on your article's publication in JOSS!

Many thanks to @yadudoc and @sarathsp06 for their reviews, and @gkthiruvathukal for editing this.

It looks like the DOI is not yet resolving, so I'm going to leave this issue open until that step is finished. You can see the final paper here: https://joss.theoj.org/papers/10.21105/joss.03075

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03075/status.svg)](https://doi.org/10.21105/joss.03075)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03075">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03075/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03075/status.svg
   :target: https://doi.org/10.21105/joss.03075
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03075/status.svg)](https://doi.org/10.21105/joss.03075)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
