### ISSUE TITLE
[PRE REVIEW]: ParticleTracker: a gui based particle tracking software

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3260]
**Submitting author:** @mikesmithlab (<a href="http://orcid.org/0000-0002-8210-1264">Michael Smith</a>)
**Repository:** <a href="https://github.com/MikeSmithLabTeam/particletracker" target ="_blank">https://github.com/MikeSmithLabTeam/particletracker</a>
**Version:** v1.0.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @alexlib, @nkeim, @tacaswell
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @mikesmithlab. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @jni.

@mikesmithlab if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.34 s (175.5 files/s, 22119.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          35           1178           1784           3095
reStructuredText                19            290            151            714
YAML                             1              1              0            146
TeX                              1             12              0             73
Markdown                         2             15              0             48
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            60           1508           1943           4111
-------------------------------------------------------------------------------


Statistical information for the repository '807d64c41bb9b6835b80da61' was
gathered on 2021/05/06.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
James                            7           103             57            0.76
JamesDownsLab                    4             4              3            0.03
Mike Smith                      23            40             61            0.48
MikeSmithLab                     3            37             55            0.43
mikesmith                        1           109             46            0.73
mikesmithlab                    89         12968           7669           97.57

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
James                        28           27.2          7.1               14.29
JamesDownsLab                 1           25.0          7.0                0.00
Mike Smith                 5923        14807.5          1.7                3.60
mikesmithlab                105            0.8          6.9                0.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/B978-0-12-391857-4.00009-4 is OK
- 10.1063/5.0003322 is OK
- 10.1049/iet-ipr.2018.5684 is OK
- 10.1016/B978-0-12-391857-4.00009-4 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1038/nmeth.2808 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03260/joss.03260/10.21105.joss.03260.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03260/joss.03260/10.21105.joss.03260.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @mikesmithlab and thanks for your submission. I'm adding the "waitlist" label to this because the relevant editors are currently overburdened. Thank you for your patience!

**Comment by Kevin-Mattheus-Moerman** [comment]
@kthyng I can take this one

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@mikesmithlab I'll be your handling editor for this submission. I will now proceed to find reviewers for this work. If you'd like to suggest reviewers at this point that would be helpful. You can mention their github names but leave out the @ symbols for the moment. Thanks.

**Comment by Kevin-Mattheus-Moerman** [comment]
@mikesmithlab  Some points to consider below. 

- [ ] Can you please check that invalid DOI in the paper, see the reference check :point_up: 
- [ ] Can you work on adding clear contribution guidelines (see [here](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) for more information)? I recommend adding a CONTRIBUTING.md file and to link to it from the README as well. In the contributing guidelines you can mention how people can contribute and also give guidelines on code style or variable naming if you like. 

Recommendations: 
- [ ] Since this package can create nice visual results to showcase performance/functionality I highly recommend including some visualizations in the JOSS paper. It would help readers to quickly grasp what the software is capable of. 
- [ ] I also highly recommend adding something like a "graphical abstract" (an image showcasing the functionality) to the README. This way people that find your repository also quickly see what it is about. 
- [ ] I recommend making the documentation link on your README an actual hyperlink, so use something like [https://particle-tracker.readthedocs.io/en/master/](https://particle-tracker.readthedocs.io/en/master/).  It is slightly more awkward at the moment to get to the link. 
- [ ] I recommend actually linking to your license file in the README to, i.e. turn the text [the MIT licence](https://github.com/MikeSmithLabTeam/particletracker/blob/master/license.txt), like shown here. 
- [ ] Once you have a CONTRIBUTING.md with contributing guidelines I recommend also adding a COC.md file which is the code of conduct for contributors. [This](https://www.contributor-covenant.org/version/2/0/code_of_conduct/code_of_conduct.md) may be a useful template to use from https://www.contributor-covenant.org/. I especially recommend this step if you aim for your project to grow and gain a lively contributor community. 

If you update the paper you can call: `@whedon generate pdf` in a comment to automatically update the paper.

**Comment by Kevin-Mattheus-Moerman** [comment]
@mikesmithlab can you work on the points highlighted :point_up:

**Comment by Kevin-Mattheus-Moerman** [comment]
@mikesmithlab :wave: can you comment on the points raised above :point_up:

**Comment by Kevin-Mattheus-Moerman** [comment]
I have sent a reminder email to the author @mikesmithlab

**Comment by mikesmithlab** [comment]
Do apologise, I will start working on the points you raise

**Comment by mikesmithlab** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03260/joss.03260/10.21105.joss.03260.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03260/joss.03260/10.21105.joss.03260.pdf) :page_facing_up: :point_left:

**Comment by mikesmithlab** [comment]
I think I've now addressed all the points you raise above, apologies about the long wait I'll check this feed more regularly now.

**Comment by mikesmithlab** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03260/joss.03260/10.21105.joss.03260.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03260/joss.03260/10.21105.joss.03260.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/B978-0-12-391857-4.00009-4 is OK
- 10.1063/5.0003322 is OK
- 10.1049/iet-ipr.2018.5684 is OK
- 10.1016/B978-0-12-391857-4.00009-4 is OK
- 10.1038/nmeth.2808 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@mikesmithlab Thanks for making those edits, I ticked those boxes. One more thing: 
- [ ] In your code of conduct document you need to `[INSERT CONTACT METHOD]`

**Comment by Kevin-Mattheus-Moerman** [comment]
@mikesmithlab at this point I'll be looking for reviewers. Let me know if you have any recommended reviewers in mind (you can mention them here but do not use the `@` in their github handles. Thanks.

**Comment by mikesmithlab** [comment]
COC now has contact method added.

Re: reviewers given the nature of the project - aimed at making things accessible to people not in the field, even those that can't code - anyone who can assess python code should be able to review.

If you are looking for more specialist opinions on particle tracking then a few ideas might be:

the authors of Trackpy https://github.com/soft-matter/trackpy this is a python particle tracking library which is actually used within our project to handle parts of the process. This is a mature library which allows the creation of particle tracking projects but does require significant coding.

There are a few authors who have written routines for particle tracking in other languages which are linked to here: http://www.physics.emory.edu/faculty/weeks//idl/ . There is one author who has written some form of GUI in IDL with a limited feature set but there doesn't appear to be a github repository.

Sorry I can't be of more help but will keep looking / thinking about alternatives

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03260/joss.03260/10.21105.joss.03260.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03260/joss.03260/10.21105.joss.03260.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@danielballan @caspervdw @nkeim @tacaswell @alexlib @GenevieveBuckley would you be interested in reviewing this work for [the Journal of Open Source Software (JOSS)](https://joss.theoj.org/)? The [review process](https://joss.readthedocs.io/en/latest/submitting.html#the-review-process) takes place on GitHub and focuses on [the software](https://github.com/MikeSmithLabTeam/particletracker) and [the short paper](https://github.com/openjournals/joss-papers/blob/joss.03260/joss.03260/10.21105.joss.03260.pdf). 

Note we can be very flexible regarding time needed to complete the review! If you can help please just let us know how much time you think we need. 

If you are new to reviewing for JOSS, here is an example of a finished review process: https://github.com/openjournals/joss-reviews/issues/3323. As you can see reviewers have a checklist to complete which guides the review process. 

Let me know if you have any questions.

**Comment by tacaswell** [comment]
This is a very cool project, but I am significantly over-subscribed.  

If you do not get anyone else to volunteer, I can probably look at this in late August / early Sept.

**Comment by Kevin-Mattheus-Moerman** [comment]
@tacaswell thanks for the reply. I understand. We can actually take the time so late August / early Sept. could be fine. I'll let you know if I end up stuck for reviewers. Thanks.

**Comment by nkeim** [comment]
I could also be a reviewer in late August/early September. I think I am marginally less over-subscribed than Tom :).

**Comment by Kevin-Mattheus-Moerman** [comment]
@danielballan @caspervdw @alexlib @GenevieveBuckley would you be interested in reviewing this work for [the Journal of Open Source Software (JOSS)](https://joss.theoj.org/)? The [review process](https://joss.readthedocs.io/en/latest/submitting.html#the-review-process) takes place on GitHub and focuses on [the software](https://github.com/MikeSmithLabTeam/particletracker) and [the short paper](https://github.com/openjournals/joss-papers/blob/joss.03260/joss.03260/10.21105.joss.03260.pdf). 

Note we can be very flexible regarding time needed to complete the review! If you can help please just let us know how much time you think we need. 

If you are new to reviewing for JOSS, here is an example of a finished review process: https://github.com/openjournals/joss-reviews/issues/3323. As you can see reviewers have a checklist to complete which guides the review process. 

Let me know if you have any questions.

**Comment by alexlib** [comment]
Sorry, very busy right now. Will be ready to take some time in a month. 
Tried to test the software but didn't find the test cases. Are they attached to the submission?

**Comment by Kevin-Mattheus-Moerman** [comment]
@alexlib starting in a month is fine if you are okay with that too. I have two other reviewers that could start at that time. We do [require](https://joss.readthedocs.io/en/latest/review_criteria.html#tests) testing and encourage automated tests. The author @mikesmithlab might be able to comment on this.

**Comment by Kevin-Mattheus-Moerman** [comment]
@tacaswell @nkeim @alexlib each of you seems to be available in a month or so. We can be flexible so this timing is acceptable. Therefore if it is okay with I would like to assign you as reviewer at this point and I will ping you in about a month, does that sound okay?

**Comment by caspervdw** [comment]
Hi @Kevin-Mattheus-Moerman , it is hard to say when and if I’ll have time the coming months- so please do not count on me for reviewing this work.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @alexlib as reviewer

**Comment by whedon** [comment]
OK, @alexlib is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @nkeim as reviewer

**Comment by whedon** [comment]
OK, @nkeim is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @tacaswell as reviewer

**Comment by whedon** [comment]
OK, @tacaswell is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@tacaswell I took the liberty of adding you as a reviewer since you responded you may be able to help late August / early September. Since that timing would work I added you just now but let me know and I can remove you if you are no longer able to help. Thanks.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3611.
