### ISSUE TITLE
[REVIEW]: fitgrid: A Python package for multi-channel event-related time series regression modeling

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3293]
**Submitting author:** @turbach (<a href="http://orcid.org/0000-0001-7993-142X">Thomas P. Urbach</a>)
**Repository:** <a href="https://github.com/kutaslab/fitgrid" target ="_blank">https://github.com/kutaslab/fitgrid</a>
**Version:** v0.5.2
**Editor:** @meg-simula
**Reviewer:** @AJQuinn, @sappelhoff
**Archive:** <a href="https://doi.org/10.5281/zenodo.3581496" target="_blank">10.5281/zenodo.3581496</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/66908a7057101f2985215a986d47ed31/status.svg)](https://joss.theoj.org/papers/66908a7057101f2985215a986d47ed31)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/66908a7057101f2985215a986d47ed31"><img src="https://joss.theoj.org/papers/66908a7057101f2985215a986d47ed31/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/66908a7057101f2985215a986d47ed31/status.svg)](https://joss.theoj.org/papers/66908a7057101f2985215a986d47ed31)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/kutaslab/fitgrid" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@AJQuinn & @sappelhoff, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @meg-simula know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/kutaslab/fitgrid">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@turbach) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/kutaslab/fitgrid">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@turbach) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
    - [x] questions on installation: https://github.com/kutaslab/fitgrid/issues/196
- [x] **Functionality:** Have the functional claims of the software been confirmed?
    - [x] https://github.com/kutaslab/fitgrid/issues/199
    - [x] https://github.com/kutaslab/fitgrid/issues/210
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
    - [x] https://github.com/kutaslab/fitgrid/issues/196
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
    - [x] https://github.com/kutaslab/fitgrid/issues/198
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
    - [x] need docs on how to run full test suite: https://github.com/kutaslab/fitgrid/issues/200
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
    - [x] https://github.com/kutaslab/fitgrid/issues/200

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
    - [x] some suggestions here: https://github.com/kutaslab/fitgrid/pull/195
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?
    - [x] https://github.com/kutaslab/fitgrid/pull/195#issuecomment-849698067

**Comment by whedon** [comment]
PDF failed to compile for issue #3293 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.11 s (735.3 files/s, 106422.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          41           1614           2443           4319
reStructuredText                28            314            271            601
YAML                             5             43            100            440
Markdown                         3             35              0             76
Jupyter Notebook                 1              0           1082             59
make                             1              8              8             21
-------------------------------------------------------------------------------
SUM:                            79           2014           3904           5516
-------------------------------------------------------------------------------


Statistical information for the repository '9e0e5a9f7892fb56c580de85' was
gathered on 2021/05/19.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Andrey Portnoy                 191          5222           5139           30.16
Lauren                          10           438             82            1.51
Tom Urbach                     119         15705           7771           68.33

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Andrey Portnoy             2405           46.1         28.4                6.99
Tom Urbach                 5971           38.0          8.8               24.10
```

**Comment by meg-simula** [comment]
:wave:  @turbach @AJQuinn @sappelhoff  this is the review thread for the paper. 

Both reviewers have checklists at the top of this thread with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines. We aim for reviews to be completed within about 2-4 weeks, but please let me know if any of you require some more time. We can also use Whedon (our bot) to set automatic reminders if you know you'll be away for a known period of time.

Please feel free to ping me (@meg-simula) if you have any questions/concerns!

**Comment by turbach** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03293/joss.03293/10.21105.joss.03293.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03293/joss.03293/10.21105.joss.03293.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
:wave: @AJQuinn, please update us on how your review is going (this is an automated reminder).

**Comment by whedon** [comment]
:wave: @sappelhoff, please update us on how your review is going (this is an automated reminder).

**Comment by sappelhoff** [comment]
I have made a first pass at the review and opened several issues and PRs that now need to be addressed (or reasonably rejected). My overall impression so far is, that fitgrid is a useful and well documented package that fills a niche. I'll make a final evaluation once all open points have been addressed by the authors (see above).

**Comment by sappelhoff** [comment]
@whedon remind @sappelhoff in 2 weeks

If I don't reply anymore, please notify me via email, that you should be able to see from my GH profile.

**Comment by whedon** [comment]
I'm sorry @sappelhoff, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by AJQuinn** [comment]
Hi all - sorry I'm a bit late, I was unexpectedlly off work for family reasons. I am working through the review now and will complete before the end of this week. Cheers

**Comment by AJQuinn** [comment]
Hello - I've completed my review of fitgrid, it works as described, has excellent testing coverage and clear documentation. I've highlighted a few points for improvement in issues on the main repo and would be happy to proceed once these are actioned.

**Comment by sappelhoff** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03293/joss.03293/10.21105.joss.03293.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03293/joss.03293/10.21105.joss.03293.pdf) :page_facing_up: :point_left:

**Comment by turbach** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03293/joss.03293/10.21105.joss.03293.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03293/joss.03293/10.21105.joss.03293.pdf) :page_facing_up: :point_left:

**Comment by turbach** [comment]
@sappelhoff @AJQuinn @andportnoy @meg-simula 

Hi all, thanks much for the reviews, close reads, and constructive comments. The JOSS ms, fitgrid package, and docs are better for them.

The revised ms is available [above](https://github.com/openjournals/joss-reviews/issues/3293#issuecomment-876094423).

The revisions to the package and docs are incorporated into a new stable release, [fitgrid v0.5.1](https://github.com/kutaslab/fitgrid/releases/tag/v0.5.1).

The corresponding linux and OSX 0.5.1 conda packages are deployed on [anaconda.org/kutaslab/fitgrid](https://anaconda.org/kutaslab/fitgrid) and the 0.5.1 docs are on [kutaslab.github.io/fitgrid](https://kutaslab.github.io/fitgrid).

The revisions were substantial and I hope fixed more errors than they introduced. In addition to patching the broken CI, and numerous corrections, the major revisions to the docs are
* expanded citations
* intersphinx links to external docs
* a substantially updated [Installation](https://kutaslab.github.io/fitgrid/installation.html#how-to-install-fitgrid)  section with new examples of installation options for mamba vs. conda, conda-forge vs. default Anaconda channels, and MKL vs. OpenBLAS libraries. 
* an entirely new section [Contributing](https://kutaslab.github.io/fitgrid/contributing.html) that includes
  * an [overview](https://kutaslab.github.io/fitgrid/contributing.html#overview-for-developers) of the version control and [continuous integration and deployment workflow](https://kutaslab.github.io/fitgrid/contributing.html#continuous-integration-and-deployment-cid) for developers.
  * [best practices](https://kutaslab.github.io/fitgrid/contributing.html#id1) for installing fitgrid from source in development mode into a compatible conda
  environment and running pytests and building the sphinx documentation.

Additional notes on specific issues and revisions are collected in this PR kutaslab/fitgrid#208

If further changes to the JOSS m.s. are in order please branch from and make the PR to [kutasab/fitgrid/joss-paper](https://github.com/kutaslab/fitgrid/tree/joss-paper).

If there are changes to the fitgrid code or docs please branch from and make the PR to [kutaslab/fitgrid/fg052dev0](https://github.com/kutaslab/fitgrid/tree/fg052dev0).

I'll be traveling and [off email](https://www.google.com/maps/place/Kearsarge+Pass/@36.7730151,-118.3767328,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipODl4OvQ-pfWIcI5eYKOxFZysvGSdNXcy1jEwxI!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipODl4OvQ-pfWIcI5eYKOxFZysvGSdNXcy1jEwxI%3Dw114-h86-k-no!7i4032!8i3024!4m5!3m4!1s0x80bfc19c7376e487:0x56fb4963071f5781!8m2!3d36.7730151!4d-118.3767328) July 8 - 14, will respond to remaining and any new issues when I return.

Thanks again.

Tom

**Comment by sappelhoff** [comment]
Thanks @turbach I have only three hopefully minor points that are left:

- [ ] https://github.com/kutaslab/fitgrid/issues/210 (this might be a problem with my machine and/or the docs, or an actual issue)
- [ ] https://github.com/kutaslab/fitgrid/issues/198 (feel free to ditch this one if you can't figure it out)
- [ ] https://github.com/kutaslab/fitgrid/pull/211 (minor PR to purge some unneeded sphinx build warnings)

**Comment by sappelhoff** [comment]
@meg-simula all my points have been addressed satisfactorily by @turbach and I am happy to recommend fitgrid for publication in JOSS.

Some issues I raised are still waiting to be resolved, but I don't consider them blockers for publication.

**Comment by AJQuinn** [comment]
Hello - agreed, I'm happy that the changes in https://github.com/kutaslab/fitgrid/pull/208 address my points. Can recommend for publication once these are merged!

**Comment by arfon** [comment]
I'm going to jump in here to help @meg-simula who is on vacation for the next few weeks.

@turbach – At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by turbach** [comment]
Hi @arfon, thanks much for stepping in.

Our software source is on [github.com/kutaslab/fitgrid](https://github.com/kutaslab/fitgrid) and we tag and release [stable versions](https://github.com/kutaslab/fitgrid/releases), most recently v0.5.1 and v0.5.2.

The changes from the JOSS reviews were already included in fitgrid v0.5.1 released on July 8. As luck would have it, on July 9 mamba 0.15.0 was released with a change in [strict channel priority](https://github.com/mamba-org/mamba/blob/master/CHANGELOG.md#0150-july-9-2021) semantics so there's a new fitgrid v0.5.2 release to patch up our [continuous integration](https://github.com/kutaslab/fitgrid/actions/runs/1043622628) and [online docs](https://kutaslab.github.io/fitgrid) for that.

As for the software archive, since late 2019 we have had [Zenodo DOI 10.5281/zenodo.3581496](https://doi.org/10.5281/zenodo.3581496) linked to the fitgrid github repo so it automatically archives each github release. This is the same Zenodo DOI we note in the JOSS submission on p. 4 line 136. It is a complete archive of the fitgrid stable releases from v0.4.7 through v0.5.1 and v0.5.2 and it names both of us JOSS submission authors, @andportnoy and myself (and also now @sappelhoff b.c. his recent PRs). Since we already have an established source archive in place, could you please take a look and see if it is acceptable for present purposes? Thanks.

**Comment by arfon** [comment]
@whedon set v0.5.2 as version

**Comment by whedon** [comment]
OK. v0.5.2 is the version.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.3581496 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3581496" target="_blank">10.5281/zenodo.3581496</a> is the archive.

**Comment by arfon** [comment]
@whedon recommend-accept from branch joss-paper

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.18637/jss.v067.i01 is OK
- 10.1016/0013-4694(54)90007-3 is OK
- 10.1016/j.jneumeth.2003.10.009 is OK
- 10.7717/peerj.7838 is OK
- 10.3389/fnins.2013.00267 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.21105/joss.00862 is OK
- 10.18637/jss.v082.i13 is OK
- 10.1007/BF00171584 is OK
- 10.1093/oxfordhb/9780195374148.001.0001 is OK
-  10.25080/Majora-92bf1922-00a  is OK
- 10.1155/2011/156869 is OK
- 10.1111/psyp.12317 is OK
- 10.1111/psyp.12320 is OK
- 10.1155/2011/879716 is OK
- 10.17605/OSF.IO/YNV9K is OK
- 10.1073/pnas.1922028117 is OK
-  10.25080/Majora-92bf1922-011  is OK
- 10.5281/zenodo.3968485 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1111/psyp.12299 is INVALID because of 'https://doi.org/' prefix
- 10.5555/1953048.2078195 is INVALID
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2461

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2461, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true from branch joss-paper 
```

**Comment by arfon** [comment]
@whedon accept deposit=true from branch joss-paper

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1417004675988131840) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2462
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03293](https://doi.org/10.21105/joss.03293)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@AJQuinn, @sappelhoff  – many thanks for your reviews here and to @meg-simula for editing this submission! JOSS relies upon the volunteer effort of people like you and we simply wouldn't be able to do this without you ✨ 

@turbach – your paper is now accepted and published in JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03293/status.svg)](https://doi.org/10.21105/joss.03293)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03293">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03293/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03293/status.svg
   :target: https://doi.org/10.21105/joss.03293
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03293/status.svg)](https://doi.org/10.21105/joss.03293)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by turbach** [comment]
Many hands make light work, thanks to all ... @andportnoy @sappelhoff @AJQuinn @meg-simula and @arfon.
