### ISSUE TITLE
[REVIEW]: ParticleTracker: a gui based particle tracking software

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3611]
**Submitting author:** @mikesmithlab (<a href="http://orcid.org/0000-0002-8210-1264">Michael Smith</a>)
**Repository:** <a href="https://github.com/MikeSmithLabTeam/particletracker" target ="_blank">https://github.com/MikeSmithLabTeam/particletracker</a>
**Version:** v1.0.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** @alexlib, @nkeim, @tacaswell
**Archive:** Pending

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/58d477d33f3191a3918baeb383658336/status.svg)](https://joss.theoj.org/papers/58d477d33f3191a3918baeb383658336)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/58d477d33f3191a3918baeb383658336"><img src="https://joss.theoj.org/papers/58d477d33f3191a3918baeb383658336/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/58d477d33f3191a3918baeb383658336/status.svg)](https://joss.theoj.org/papers/58d477d33f3191a3918baeb383658336)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/MikeSmithLabTeam/particletracker" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@alexlib & @nkeim & @tacaswell, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @Kevin-Mattheus-Moerman know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @alexlib
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/MikeSmithLabTeam/particletracker">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [ ] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/MikeSmithLabTeam/particletracker">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Contribution and authorship:** Has the submitting author (@mikesmithlab) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [ ] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @nkeim
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/MikeSmithLabTeam/particletracker">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [ ] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/MikeSmithLabTeam/particletracker">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Contribution and authorship:** Has the submitting author (@mikesmithlab) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [ ] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @tacaswell
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/MikeSmithLabTeam/particletracker">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [ ] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/MikeSmithLabTeam/particletracker">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Contribution and authorship:** Has the submitting author (@mikesmithlab) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [ ] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @alexlib, @nkeim, @tacaswell it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by nkeim** [comment]
@Kevin-Mattheus-Moerman I was vacationing and my invitation expired. Could you please have a new one issued?

**Comment by alexlib** [comment]
I raised some issues about functionality on the respective repo
https://github.com/MikeSmithLabTeam/particletracker/issues/2
https://github.com/MikeSmithLabTeam/particletracker/issues/3

is this is the right way to handle this review?

**Comment by kthyng** [comment]
@whedon re-invite @nkeim as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@nkeim please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by kthyng** [comment]
@nkeim please use the link above as your invitation

@alexlib Yep — just be sure to add a link to this review issue in the issues to keep everything connected together.

**Comment by nkeim** [comment]
> 👋 @nkeim, please update us on how your review is going (this is an automated reminder).

I'm getting started and hope to do this in the coming week.

@whedon generate pdf

**Comment by mikesmithlab** [comment]
I have now uploaded 7 screencast videos that cover the overview and 6 examples. Hopefully these make it much simpler to work through the different examples.

**Comment by mikesmithlab** [comment]
There is a small issue that I have uncovered which is slightly out of my control at the moment. We have a testdata folder on the github repository. This is fine and works perfectly. We also have a copy on my personal webpage which is hosted by my university. The university has been upgrading the webpages and for some reason seems to be hosting an old version of the website. I also can't access it at the moment! I am working to resolve this but please be aware that you should use the testdata.zip available on the github page. I do apologise if this has caused any issues I will try to resolve as soon as possible

**Comment by alexlib** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by alexlib** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/B978-0-12-391857-4.00009-4 is OK
- 10.1063/5.0003322 is OK
- 10.1049/iet-ipr.2018.5684 is OK
- 10.1016/B978-0-12-391857-4.00009-4 is OK
- 10.1038/nmeth.2808 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by alexlib** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03611/joss.03611/10.21105.joss.03611.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03611/joss.03611/10.21105.joss.03611.pdf) :page_facing_up: :point_left:

**Comment by alexlib** [comment]
> 👋 @alexlib, please update us on how your review is going (this is an automated reminder).

I completed my review and happy to recommend this work for publication

**Comment by mikesmithlab** [comment]
> There is a small issue that I have uncovered which is slightly out of my control at the moment. We have a testdata folder on the github repository. This is fine and works perfectly. We also have a copy on my personal webpage which is hosted by my university. The university has been upgrading the webpages and for some reason seems to be hosting an old version of the website. I also can't access it at the moment! I am working to resolve this but please be aware that you should use the testdata.zip available on the github page. I do apologise if this has caused any issues I will try to resolve as soon as possible

This issue has now been resolved. The testdata on my personal webpage is now up to date.

**Comment by Kevin-Mattheus-Moerman** [comment]
@alexlib thanks for your help with this review. If you are fully satisfied are you able to tick all boxes? If not there may be some issues that still need to be resolved. Thanks again!

**Comment by alexlib** [comment]
> @alexlib thanks for your help with this review. If you are fully satisfied are you able to tick all boxes? If not there may be some issues that still need to be resolved. Thanks again!

It' lacks automated tests

**Comment by Kevin-Mattheus-Moerman** [comment]
@mikesmithlab are you able to add clearly documented automated (or manual) tests?

**Comment by mikesmithlab** [comment]
> @mikesmithlab are you able to add clearly documented automated (or manual) tests?

In our installation instructions on readthedocs:
https://particle-tracker.readthedocs.io/en/master/rstfiles/installation.html

the last section says:
"Verifying the installation
To verify that the installation is working correctly you should read the getting started section which explains how to launch the software for both the precompiled and python versions. Once you have done this there are 5 example videos which also act as tutorials which should enable you to verify and test the core functionality of the software."

The tests are not automated but in examples 2,3,4&5 one simply opens the gui, loads a settings file and then clicks the process button. Each example has its own page and walk through video which explains and shows what the expected behaviour / output should be.

Could you clarify what changes are being asked for as I'd assumed that this would satisfy the manual test request?

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks for the explanation @mikesmithlab. 

@alexlib What is described sounds like reasonably documented manual steps. Which are acceptable in principle. If you agree, you could consider ticking that last box. Thanks again for your help here!

**Comment by Kevin-Mattheus-Moerman** [comment]
@nkeim could you provide an update on this review? Thanks again for your help!

**Comment by alexlib** [comment]
> Thanks for the explanation @mikesmithlab.
> 
> @alexlib What is described sounds like reasonably documented manual steps. Which are acceptable in principle. If you agree, you could consider ticking that last box. Thanks again for your help here!

everything is checked in @Kevin-Mattheus-Moerman

**Comment by nkeim** [comment]
> @nkeim could you provide an update on this review? Thanks again for your help!

Thanks for checking in! Sorry for my slowness; another review needed extra time last week. I should be able to finish this review this week.

**Comment by Kevin-Mattheus-Moerman** [comment]
@nkeim great, thanks!

**Comment by nkeim** [comment]
A couple quick comments related to my remaining checklist items for the paper:
1. The authors might want to double-check the author initials, at least for trackpy; "et al" might be appropriate. Also, I recommend citing the [trackpy Zenodo DOI](https://zenodo.org/record/3492186#.YUDl3C1h3UY) for the sake of automated citation-tracking.
2. There are sophisticated particle-tracking GUIs for FIJI (ImageJ) that seem to have wide adoption especially in the life sciences. [TrackMate](https://imagej.net/plugins/trackmate/) is one prominent example. I think it's worth citing at least one because it's another high-quality example of the state of the field, even though the overlap with ParticleTracker's intended user base may not be large.

I'm nearly done with my review (it's great!) but first need to create some issues on the software repository (and possibly mention a couple other things here).

**Comment by Kevin-Mattheus-Moerman** [comment]
@mikesmithlab :point_up: can you have a look at these comments?

**Comment by Kevin-Mattheus-Moerman** [comment]
@tacaswell thanks again for agreeing to help review this work. I think I remember you saying you'd be able to help around mid-September. This comment is just to check in with you to see how you are doing. Are you able to start with this review soon? Thanks.

**Comment by nkeim** [comment]
I've created the 8 above-referenced issues in the software repository, none of which I think should hold up publication. Aside from my remaining checklist items mentioned above, I am done and I am happy to recommend publication. I especially appreciate the tutorial videos and the range of representative examples, and I think the software is a good fit to the stated use case of basic particle tracking for research. Thanks!

**Comment by mikesmithlab** [comment]
> A couple quick comments related to my remaining checklist items for the paper:
> 
> 1. The authors might want to double-check the author initials, at least for trackpy; "et al" might be appropriate. Also, I recommend citing the [trackpy Zenodo DOI](https://zenodo.org/record/3492186#.YUDl3C1h3UY) for the sake of automated citation-tracking.
> 2. There are sophisticated particle-tracking GUIs for FIJI (ImageJ) that seem to have wide adoption especially in the life sciences. [TrackMate](https://imagej.net/plugins/trackmate/) is one prominent example. I think it's worth citing at least one because it's another high-quality example of the state of the field, even though the overlap with ParticleTracker's intended user base may not be large.
> 
> I'm nearly done with my review (it's great!) but first need to create some issues on the software repository (and possibly mention a couple other things here).

I've checked initials, and changed / added the suggested citation to the paper.bib file.  I've resolved some of the issues above. The issue about smoothing needs some more info to resolve. The other two may be small bugs that I think I can resolve fairly easily. Thanks for your efforts, much appreciated.

**Comment by nkeim** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03611/joss.03611/10.21105.joss.03611.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03611/joss.03611/10.21105.joss.03611.pdf) :page_facing_up: :point_left:

**Comment by nkeim** [comment]
@mikesmithlab Thanks! One small final request: it's probably best practice to link to https://doi.org/10.5281/zenodo.3492186 instead of the zenodo.org page for trackpy. In any case I'm happy to sign off and I have checked all my boxes.

**Comment by mikesmithlab** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03611/joss.03611/10.21105.joss.03611.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03611/joss.03611/10.21105.joss.03611.pdf) :page_facing_up: :point_left:

**Comment by mikesmithlab** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03611/joss.03611/10.21105.joss.03611.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03611/joss.03611/10.21105.joss.03611.pdf) :page_facing_up: :point_left:

**Comment by mikesmithlab** [comment]
Not sure what I'm doing wrong. On the paper.bib file the url is "https://doi.org/10.5281/zenodo.3492186" but in the proof it reverts to https://zenodo.org........

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/B978-0-12-391857-4.00009-4 is OK
- 10.1063/5.0003322 is OK
- 10.1049/iet-ipr.2018.5684 is OK
- 10.1016/B978-0-12-391857-4.00009-4 is OK
- 10.1038/nmeth.2808 is OK

MISSING DOIs

- 10.1016/j.ymeth.2016.09.016 may be a valid DOI for title: TrackMate: An open and extensible platform for single-particle tracking

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@mikesmithlab is that citation issue resolved now? Let me know if I can help. Also can you check this potentially missing DOI :point_up: ?

**Comment by mikesmithlab** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/B978-0-12-391857-4.00009-4 is OK
- 10.1063/5.0003322 is OK
- 10.1049/iet-ipr.2018.5684 is OK
- 10.1016/B978-0-12-391857-4.00009-4 is OK
- 10.1038/nmeth.2808 is OK

MISSING DOIs

- 10.1016/j.ymeth.2016.09.016 may be a valid DOI for title: TrackMate: An open and extensible platform for single-particle tracking

INVALID DOIs

- None
```

**Comment by mikesmithlab** [comment]
@whendon generate pdf

**Comment by mikesmithlab** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03611/joss.03611/10.21105.joss.03611.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03611/joss.03611/10.21105.joss.03611.pdf) :page_facing_up: :point_left:

**Comment by mikesmithlab** [comment]
Citation issue seems to be resolved now

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/B978-0-12-391857-4.00009-4 is OK
- 10.1063/5.0003322 is OK
- 10.1049/iet-ipr.2018.5684 is OK
- 10.1016/B978-0-12-391857-4.00009-4 is OK
- 10.1038/nmeth.2808 is OK

MISSING DOIs

- 10.1016/j.ymeth.2016.09.016 may be a valid DOI for title: TrackMate: An open and extensible platform for single-particle tracking

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@mikesmithlab is that missing DOI fixable too? :point_up:

**Comment by Kevin-Mattheus-Moerman** [comment]
@tacaswell are you able to pick up the review at this point too?

**Comment by mikesmithlab** [comment]
> ```
> Reference check summary (note 'MISSING' DOIs are suggestions that need verification):
> 
> OK DOIs
> 
> - 10.1016/B978-0-12-391857-4.00009-4 is OK
> - 10.1063/5.0003322 is OK
> - 10.1049/iet-ipr.2018.5684 is OK
> - 10.1016/B978-0-12-391857-4.00009-4 is OK
> - 10.1038/nmeth.2808 is OK
> 
> MISSING DOIs
> 
> - 10.1016/j.ymeth.2016.09.016 may be a valid DOI for title: TrackMate: An open and extensible platform for single-particle tracking
> 
> INVALID DOIs
> 
> - None
> ```

Hi I'm not sure what I need to do to fix this. The "Missing DOIs" cites a doi that points to the correct article. However, this is the same DOI which is in my paper.bib file. That DOI also appears correctly in the preprint generated above.

**Comment by Kevin-Mattheus-Moerman** [comment]
@mikesmithlab hmmm okay thanks. I'll alert @openjournals/dev but it looks like this should be fine.

**Comment by danielskatz** [comment]
@mikesmithlab - the problem here is that you have not put some DOIs into the bib file as DOIs, but instead, as URLs.

See https://github.com/MikeSmithLabTeam/particletracker/pull/12 for a fix.  (I'm also removing the URLs that duplicate DOIs, though I think whedon just ignores these in favor of the DOIs anyhow)

**Comment by mikesmithlab** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.ymeth.2016.09.016 is OK
- 10.5281/zenodo.3492186 is OK
- 10.1016/B978-0-12-391857-4.00009-4 is OK
- 10.1063/5.0003322 is OK
- 10.1049/iet-ipr.2018.5684 is OK
- 10.1016/B978-0-12-391857-4.00009-4 is OK
- 10.1038/nmeth.2808 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mikesmithlab** [comment]
> @mikesmithlab - the problem here is that you have not put some DOIs into the bib file as DOIs, but instead, as URLs.
> 
> See [MikeSmithLabTeam/particletracker#12](https://github.com/MikeSmithLabTeam/particletracker/pull/12) for a fix. (I'm also removing the URLs that duplicate DOIs, though I think whedon just ignores these in favor of the DOIs anyhow)

thanks @danielskatz 

@Kevin-Mattheus-Moerman  I think this is all fixed now

**Comment by Kevin-Mattheus-Moerman** [comment]
@mikesmithlab nothing from your end. We'd like the last reviewer to complete the review, and I will send another reminder now.

**Comment by Kevin-Mattheus-Moerman** [comment]
@tacaswell would you be able to pick up the review process at this point? Thanks!

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon re-invite @tacaswell as reviewer
