### ISSUE TITLE
[REVIEW]: GiNaCDE: the high-performance F-expansion and First Integral Methods with C++ library for solving Nonlinear Differential Equations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3885]
**Submitting author:** @mithun218 (<a href="http://orcid.org/0000-0002-9678-4625">Mithun Bairagi</a>)
**Repository:** https://github.com/mithun218/GiNaCDE
**Branch with paper.md** (empty if default branch): 
**Version:** v1.5.0
**Editor:** @meg-simula
**Reviewers:** @peanutfun, @carstenbauer
**Archive:** 10.5281/zenodo.6366056

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/340d71bea413f1f5677108636bf38665/status.svg)](https://joss.theoj.org/papers/340d71bea413f1f5677108636bf38665)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/340d71bea413f1f5677108636bf38665"><img src="https://joss.theoj.org/papers/340d71bea413f1f5677108636bf38665/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/340d71bea413f1f5677108636bf38665/status.svg)](https://joss.theoj.org/papers/340d71bea413f1f5677108636bf38665)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/mithun218/GiNaCDE" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@peanutfun & @carstenbauer, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @meg-simula know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @peanutfun
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/mithun218/GiNaCDE">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mithun218/GiNaCDE">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mithun218) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @carstenbauer
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/mithun218/GiNaCDE">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mithun218/GiNaCDE">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mithun218) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @peanutfun, @carstenbauer it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 962

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/S0375-9601(02)01775-9 is OK
- 10.1155/2013/104894 is OK
- 10.1016/j.chaos.2005.10.007 is OK
- 10.1016/S0960-0779(03)00102-4 is OK
- 10.1016/S0375-9601(01)00825-8 is OK
- 10.15388/NA.17.4.14052 is OK
- 10.1016/j.amc.2010.04.026 is OK
- 10.1006/jsco.2001.0494 is OK
- 10.1016/j.jmaa.2010.08.050 is OK
- 10.1016/0010-4655(96)00104-X is OK
- 10.1016/S0010-4655(02)00559-3 is OK
- 10.1016/j.jsc.2003.09.004 is OK
- 10.1016/j.cpc.2004.08.007 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.19 s (227.5 files/s, 68429.5 lines/s)
-----------------------------------------------------------------------------------
Language                         files          blank        comment           code
-----------------------------------------------------------------------------------
C++                                 23           1943            679           7981
TeX                                  2            144             15            925
C/C++ Header                        11            221            106            643
CMake                                3             54             64            219
Markdown                             3             47              0            167
YAML                                 1              1              4             18
Windows Resource File                1              0              0              1
-----------------------------------------------------------------------------------
SUM:                                44           2410            868           9954
-----------------------------------------------------------------------------------


Statistical information for the repository '5677997e600bb1d677520f81' was
gathered on 2021/11/03.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
mithun218                        3         12874           1301          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
mithun218                 11573           89.9          0.0                6.81
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03885/joss.03885/10.21105.joss.03885.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03885/joss.03885/10.21105.joss.03885.pdf) :page_facing_up: :point_left:

**Comment by meg-simula** [comment]
👋🏼 @mithun218 @peanutfun  @carstenbauer  this is the review thread for the paper. All of our communications will happen here from now on.

Both reviewers have checklists at the top of this thread with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention `openjournals/joss-reviews#REVIEW_NUMBER` so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for reviews to be completed within about 2-4 weeks. Please let me know if any of you require some more time.

Please feel free to ping me (@meg-simula ) if you have any questions/concerns.

**Comment by peanutfun** [comment]
Hi @mithun218 👋 I'll review your software in the next couple of days, and open up issues in the repository as I go along. Some of them might only be suggestions and you won't have to resolve all of them to get your submission accepted (from my side). Once I'm finished, I'll hence report back here and summarize the issues with respect to the review criteria and the checklist above.

Happy coding!

**Comment by peanutfun** [comment]
@mithun218 Before I can summarize I need a bit of clarification on how to use and interpret the output of GiNaCDE. I very much like the extensive documentation you provide, with an in-depth look at the mathematical methods and clear instructions on how to use GiNaCDE. However, it does not explain how to use the resulting output (files). That's why I have some trouble verifying if the software computes the correct solutions.

Admittedly, I am not too familiar with the methods you use and the problems you try to solve, so I might have a wrong impression or perspective. Considering the [example usage](https://github.com/mithun218/GiNaCDE#example-usage) you propose in the `README.md`, how would a typical workflow look like after calculating a solution? In particular: What to do with the resulting output `.txt` file? Its contents do not seem self-explanatory to me.

GiNaCDE provides the option to output either in the Maple or the Mathematica format. However, the output files also contain plain text and cannot simply be "imported" into either of the programs (Please, correct me if I'm wrong!). How could I use the output of GiNaCDE in them? Would I need to copy-paste the expressions, leaving out the text? How do I get a "computational" representation of the results to continue on with?

I myself own neither of the programs. How can I make use of the results in my case?

**Comment by mithun218** [comment]
@peanutfun thanks so much for your review and comments. 
I am happy to edit the paper to incorporate your comments.

The GiNaCDE software determines exact solutions with calculating steps, and the results are saved in an output .txt file in the Maple or the Mathematica format. In order to use the output exact solutions in Maple or Mathematica software, we have to copy the exact solutions with the conditions of solutions (which are also provided in the output .txt file) from the output .txt file. Then, we can verify the exact solutions using Maple or Mathematica software. To verify the exact solutions at first, we have to substitute the exact solutions with the corresponding conditions of the solutions into the input NLPDE and then simplify it. After simplification, if it is equal to zero, then the solution is correct. Otherwise, the solution is not valid.

Besides the output .txt file, the solutions of the NLPDE and the corresponding conditions are also collected by the variables _solutionClt_ and _constraints_. We have explained about these variables in the section **11. INPUT AND OUTPUT OF LIBRARY** of [the documentation file](https://github.com/mithun218/GiNaCDE/blob/master/doc/documentation.pdf). Using these variables, one can easily locate and copy the solutions with the conditions of the solutions in the Maple or the Mathematica software.

 Unfortunately, currently, GiNaCDE is unable to verify the solutions without Maple or the Mathematica software. But this will be a very interesting feature of the GiNaCDE if the GiNaCDE itself is able to verify the solutions. Now I am planning that I shall add this feature in the next release of GiNaCDE but this will take some time.

I will try to resolve all the above issues (mentioned by you) in the next few days.

**Comment by peanutfun** [comment]
@mithun218 thank you for your quick reply. Indeed, I missed the part on `solutionClt` and `constraints`. Let me summarize my review and get back to my question:

You obviously put a lot of effort into implementing the F-expansion and first integral methods in an open-source framework. Your documentation focuses strongly on the intricate mathematics involved in these methods, and admittedly, they are a bit out of my reach (I'm a physicist 🙈 ). Your paper makes a good point why GiNaCDE is needed, especially in the open-source context. And I really like the GUI, it works intuitively and is a great option for users that are less familiar with the command line and C++ programming.

While GiNaCDE probably serves you well in your own workflow, the focus shifts from functionality to usability when it comes to a software publication. The goal is to address a wider audience for the software, and even people who are unfamiliar with the methods (like me) need to quickly understand how the software is installed, how they interact with it, how they use its results in their own workflow, and that everything works as intended. I find that GiNaCDE as a software package lacks this wider perspective to some degree.

Most importantly, it is very difficult for me (as somebody unfamiliar with the mathematics) to verify the results of GiNaCDE. This verification is best done automatically in tests, but as I pointed out in mithun218/GiNaCDE#3, the currently implemented tests do not verify the results. In your reply you point out that Maple or Mathematica are required for this. But you also state that

> To verify the exact solutions at first, we have to substitute the exact solutions with the corresponding conditions of the solutions into the input NLPDE and then simplify it. After simplification, if it is equal to zero, then the solution is correct. Otherwise, the solution is not valid.

Isn't this procedure also possible within GiNaCDE? Could this be used to test your results in a general way? If not, you could have the tests compute solutions for relatively simple ODEs or PDEs, and then evaluate the resulting expressions for some known function values like roots, maxima, etc. I focus on this because (automated) tests for verifying the software are part of the JOSS review criteria, and I cannot check this off until there is at least a manual procedure documented on how to verify the results of the library.

Also with regard to usability, I think the installation instructions need to be improved to account for different operating systems, and the usage instructions should show how other CMake projects can incorporate GiNaCDE. This leads me to the following list of issues we need to resolve to match the JOSS review criteria from my perspective:

### Issues for meeting review criteria

- [ ] Improve the automated tests to verify computation results (or add manual instructions on how to do so): mithun218/GiNaCDE#3
- [ ] Simplify installation instructions for Linux, and possibly add instructions for macOS and Windows: mithun218/GiNaCDE#5
- [ ] Add instructions on how to use GiNaCDE in downstream modules: mithun218/GiNaCDE#8
- [ ] Incorporate or conclusively reject suggestions to the JOSS paper: mithun218/GiNaCDE#12

Personally, I consider all other issues I opened in the GiNaCDE repository *non-crucial* for accepting your submission.

**Comment by whedon** [comment]
:wave: @peanutfun, please update us on how your review is going (this is an automated reminder).

**Comment by whedon** [comment]
:wave: @carstenbauer, please update us on how your review is going (this is an automated reminder).

**Comment by mithun218** [comment]
Hi @peanutfun Thank you for the detailed review and the valuable suggestions. I am working on them.
I went through your suggestion:

>  Improve the automated tests to verify computation results (or add manual instructions on how to do so): Make tests actually check the computation results mithun218/GiNaCDE#3

and  did just as you suggested, more or less [here.](https://github.com/mithun218/GiNaCDE/pull/16) 


1. To check solutions using GiNaCDE we have added _ginac_ output format.
2. To verify computation results we have added checkSolu() function (this function is in primary stage, currently it cannot verify some solutions).
3. We have provided some Maple worksheet, Mathematica notebook and cpp files which illustrate how to test the solutions using Maple, Mathematica and GiNaCDE software, respectively. 

Please let us know if we can do anything else.

**Comment by mithun218** [comment]
Hi @peanutfun I went through your suggestion:

> Simplify installation instructions for Linux, and possibly add instructions for macOS and Windows: Add OS-dependent installation instructions mithun218/GiNaCDE#5

and did just as you suggested, more or less [here](https://github.com/mithun218/GiNaCDE/pull/18) and [here](https://github.com/mithun218/GiNaCDE/pull/19).

1. I have updated README and documentation files as you suggested in [this](https://github.com/mithun218/GiNaCDE/issues/5) issue.
2. I have removed the tar balls as proposed in [this](https://github.com/mithun218/GiNaCDE/issues/6) issue.

Please let us know if we can do anything more.

**Comment by mithun218** [comment]
Hi @peanutfun I went through your suggestion:

>  Add instructions on how to use GiNaCDE in downstream modules: Support and advertise usage in downstream build systems mithun218/GiNaCDE#8

and did just as you suggested, more or less [here](https://github.com/mithun218/GiNaCDE/pull/20).

1. I have updated README file as you proposed in [this](https://github.com/mithun218/GiNaCDE/issues/8) issue.

Please let us know if we can do anything more.

**Comment by mithun218** [comment]
Hi @peanutfun I went through your suggestion:
> Incorporate or conclusively reject suggestions to the JOSS paper: Improve the JOSS paper mithun218/GiNaCDE#12

and did just as you suggested, more or less [here](https://github.com/mithun218/GiNaCDE/pull/21).

Please let us know if we can do anything more.

**Comment by peanutfun** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03885/joss.03885/10.21105.joss.03885.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03885/joss.03885/10.21105.joss.03885.pdf) :page_facing_up: :point_left:

**Comment by mithun218** [comment]
> joss paper correction mithun218/GiNaCDE#24

I again went through the paper, and I changed only one word.
The change is:
on the base of ⇾ on the basis of

**Comment by mithun218** [comment]
@peanutfun  I have addressed all the issues you referenced  [here](https://github.com/openjournals/joss-reviews/issues/3885#issuecomment-965388988) . Please review and if I have missed anything please let me know.

**Comment by peanutfun** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03885/joss.03885/10.21105.joss.03885.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03885/joss.03885/10.21105.joss.03885.pdf) :page_facing_up: :point_left:

**Comment by peanutfun** [comment]
@mithun218 Thank you for resolving the major issue of automated tests, and the other issues I brought up as critical for the review.

@meg-simula I finished my review and I endorse GiNaCDE for publication.

**Comment by meg-simula** [comment]
@mithun218 and @peanutfun Thanks for the review and response and resolution of the issues! @carstenbauer  Could you please update us on the progress of your review?

**Comment by carstenbauer** [comment]
@meg-simula Sorry for the delay, I will finish my review by Monday.

**Comment by meg-simula** [comment]
Excellent, we much appreciate your expertise and willingness to review.

**Comment by carstenbauer** [comment]
Alright, I've finished my review and have completed the checklist in the OP. I think that both the GiNaCDE software as well as the manuscript meets all of the JOSS criteria (in particular after the improvements triggered by @peanutfun's comments). The software has a clear purpose, is well and extensively documented (in particular from a methods point of view) and works as expected (I tested the included examples as well as a simple self-created example). Given that the raised issues below will be addressed soon, I happily endorse GiNaCDE for publication.

(Note that I did not test / review the optional GUI component.)

### Issues related to my review
* [ ] Instructions for non-systemwide installation - https://github.com/mithun218/GiNaCDE/issues/29
* [ ] Improve documentation for how to run the tests - https://github.com/mithun218/GiNaCDE/issues/30
* [ ] Revise structure of README.md - https://github.com/mithun218/GiNaCDE/issues/31

**Comment by mithun218** [comment]
@carstenbauer  Thank you for your review and valuable suggestions.  I have addressed all the issues you referenced [here](https://github.com/openjournals/joss-reviews/issues/3885#issuecomment-1025749433) . Please check these, and if I have missed anything, please let me know.

**Comment by carstenbauer** [comment]
@mithun218 Great, LGTM now.

@meg-simula My points have been adequately addressed. I therefore endorse GiNaCDE for publication in JOSS.

**Comment by meg-simula** [comment]
@editorialbot generate pdf

**Comment by meg-simula** [comment]
@editorialbot check references

**Comment by meg-simula** [comment]
@editorialbot generate pdf

**Comment by meg-simula** [comment]
@mithun218 Thank you for your submission and for successfully handling all reviewer comments. 

I have read through the paper, and find a number of relatively minor grammatical errors. Could you please proof-read the manuscript carefully for grammar before I proceed with this submission? 

Some specific points to address are 
[ ] Replace "various researches" with "various research"
[ ] Replace "scientific community fields" with "scientific fields"
[ ] Insert "a" to replace "is dependent variable" by "is a dependent variable"
[ ] Replace "a polynomial about u" by "a polynomial in u"
[ ] Insert "and" before "Kudryashov-Sinelshchikov equation". 
[ ] Replace "engineer" by "engineering"

**Comment by mithun218** [comment]
Thank you so much @meg-simula. I have carefully read through the paper and fixed all the grammatical errors [here](https://github.com/mithun218/GiNaCDE/pull/37) and [here](https://github.com/mithun218/GiNaCDE/pull/38). Please check these.

**Comment by meg-simula** [comment]
@editorialbot generate pdf

**Comment by meg-simula** [comment]
@editorialbot check references

**Comment by meg-simula** [comment]
Very good, thank you! At this point could you:
- [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g., figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata. This includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it). You may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

I can then move forward with accepting the submission.

**Comment by mithun218** [comment]
@meg-simula  I have addressed all the points you mentioned [here.](https://github.com/openjournals/joss-reviews/issues/3885?msclkid=754d7248b89811ec85a8b80f379ac4b7#issuecomment-1064043823) Please review and if I have missed anything please let me know.

**Comment by meg-simula** [comment]
@editorialbot set 10.5281/zenodo.6366056 as archive

**Comment by meg-simula** [comment]
@editorialbot recommend-accept

**Comment by arfon** [comment]
@mithun218 – I've made some fixes to the citation formatting in the PR: https://github.com/mithun218/GiNaCDE/pull/40

**Comment by mithun218** [comment]
> @mithun218 – I've made some fixes to the citation formatting in the PR:  mithun218/GiNaCDE#40

Thanks @arfon, the pull request has been merged.

**Comment by mithun218** [comment]
@arfon  We have made a tagged release of the software, and the version tag of the archived version is v1.5.0. But I have seen a problem that [here](https://github.com/openjournals/joss-reviews/issues/3885#issue-1043454555)  the version is still showing v1.0.0.

**Comment by arfon** [comment]
@editorialbot set v1.5.0 as version

**Comment by arfon** [comment]
@editorialbot accept

**Comment by arfon** [comment]
@peanutfun, @carstenbauer – many thanks for your reviews here and to @meg-simula for editing this submission! JOSS relies upon the volunteer effort of people like you and we simply wouldn't be able to do this without you ✨ 

@mithun218 – your paper is now accepted and published in JOSS :zap::rocket::boom:

**Comment by peanutfun** [comment]
@mithun218 congratulations! 🎉

**Comment by mithun218** [comment]
Huge thank you to @peanutfun and @carstenbauer  for your reviews, and @meg-simula  and @arfon for your editorial work. Much appreciated! 🎉
