### ISSUE TITLE
[REVIEW]: Kamodo: A functional api for space weather models and data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4053]
**Submitting author:** @asherp (<a href="http://orcid.org/0000-0002-5718-1303">Asher Pembroke</a>)
**Repository:** https://github.com/EnsembleGovServices/kamodo-core
**Branch with paper.md** (empty if default branch): 
**Version:** 22.6.0
**Editor:** @dfm
**Reviewers:** @dstansby, @samaloney
**Archive:** 10.5281/zenodo.6773395

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/420814228c78a09ea50c7ba720953308/status.svg)](https://joss.theoj.org/papers/420814228c78a09ea50c7ba720953308)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/420814228c78a09ea50c7ba720953308"><img src="https://joss.theoj.org/papers/420814228c78a09ea50c7ba720953308/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/420814228c78a09ea50c7ba720953308/status.svg)](https://joss.theoj.org/papers/420814228c78a09ea50c7ba720953308)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/EnsembleGovServices/kamodo-core" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@dstansby & @samaloney, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @dfm know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @dstansby
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/EnsembleGovServices/kamodo-core">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/EnsembleGovServices/kamodo-core">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@asherp) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed? https://github.com/EnsembleGovServices/kamodo-core/issues/24, https://github.com/EnsembleGovServices/kamodo-core/issues/54
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution. https://github.com/EnsembleGovServices/kamodo-core/issues/19
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)? https://github.com/EnsembleGovServices/kamodo-core/issues/28, https://github.com/EnsembleGovServices/kamodo-core/issues/58, https://github.com/EnsembleGovServices/kamodo-core/issues/59
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified? https://github.com/EnsembleGovServices/kamodo-core/issues/21, https://github.com/EnsembleGovServices/kamodo-core/issues/61
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support https://github.com/EnsembleGovServices/kamodo-core/issues/20

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages? https://github.com/EnsembleGovServices/kamodo-core/issues/62
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)? https://github.com/EnsembleGovServices/kamodo-core/issues/62

## Review checklist for @samaloney

See below in: https://github.com/openjournals/joss-reviews/issues/4053#issuecomment-1054449513

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @dstansby, @samaloney it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1439

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1051/0004-6361/201322068 is OK
- 10.5281/zenodo.2537188 is OK
- 10.5281/zenodo.1199703 is OK
- 10.1029/2018JA025297 is OK
- 10.5281/zenodo.4313063 is OK
- 10.7717/peerj-cs.103 is OK
- 10.1016/j.jastp.2004.07.030 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.5281/zenodo.3509134 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1029/2010JA016023 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=7.94 s (10.7 files/s, 2021.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          15           1310            637           4648
Markdown                         7           1030              0           1527
Jupyter Notebook                11              0           4411            550
SVG                             33              1              1            417
YAML                            10             31             25            332
TeX                              1             24              1            293
CSS                              1             47             77            291
HTML                             3             48              1            165
JavaScript                       1             43              6             83
Dockerfile                       1              8             17             13
Bourne Shell                     1              2              0              3
TOML                             1              0              0              2
-------------------------------------------------------------------------------
SUM:                            85           2544           5176           8324
-------------------------------------------------------------------------------


Statistical information for the repository '393e01f6fab58055f645e8c4' was
gathered on 2022/01/12.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Asher Pembroke                 130          6721           8902           27.18
Darren De Zeeuw                 44         17018           4203           36.92
Lutz Rastaetter                 16          4664            125            8.33
Michael Hirsch, Ph.D             1             1             31            0.06
asherp                          44          4463            599            8.81
iamjavaexpert                    5           820            259            1.88
rebeccaringuette                19          7152           2521           16.83

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Asher Pembroke             5926           88.2         13.8                8.08
Michael Hirsch, Ph.D          1          100.0         25.6                0.00
iamjavaexpert               798           97.3         11.6                0.75
rebeccaringuette              2            0.0          2.2               50.00
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04053/joss.04053/10.21105.joss.04053.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04053/joss.04053/10.21105.joss.04053.pdf) :page_facing_up: :point_left:

**Comment by dfm** [comment]
@asherp, @dstansby, @samaloney – This is the review thread for the paper. All of our communications will happen here from now on. Thanks again for agreeing to participate!

Please read the "Reviewer instructions & questions" in the first comment above.

Both reviewers have checklists at the top of this thread (in that first comment) with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention `openjournals/joss-reviews#4053` so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for the review process to be completed within about 4-6 weeks but please try to make a start ahead of this as JOSS reviews are by their nature iterative and any early feedback you may be able to provide to the author will be very helpful in meeting this schedule.

**Comment by dstansby** [comment]
👋 all. I'm afraid I am away for the next two weeks, so won't get a complete review finished before then. I have done a preliminary pass of the documentation and code, checked off some items, and opened issues (linked in the original post) for other items that need resolving. When I get back I will finish running the examples given in the documentation to check they work as expected.

@samaloney, I would suggest you start by reviewing the paper and providing any feedback on that - that way hopefully a 'complete' set of feedback is available to @asherp to be working on. Sorry again for the delay in my full review.

**Comment by whedon** [comment]
:wave: @samaloney, please update us on how your review is going (this is an automated reminder).

**Comment by whedon** [comment]
:wave: @dstansby, please update us on how your review is going (this is an automated reminder).

**Comment by dfm** [comment]
@dstansby, @samaloney — sorry about the bot messages!

@dstansby — thanks for the update and all your review comments so far. No stress! See you in two weeks.

**Comment by samaloney** [comment]
Sorry for the long delay will have this done in the next day or two.

**Comment by samaloney** [comment]
Hum for some reason I can't edit the issue template perhaps the invitation expired?

**Comment by arfon** [comment]
@editorialbot re-invite @samaloney as reviewer

**Comment by dfm** [comment]
@samaloney — sorry about that! We're in the process of transitioning to a new workflow over here. Instead of using the checklist above (I'll actually remove it), can you write a comment that starts with `@editorialbot generate my checklist`? Then the bot will overwrite that comment with a checklist that you _can_ edit, and then we'll use that one. Thanks!

**Comment by samaloney** [comment]
No worries will do that now, thanks.

**Comment by samaloney** [comment]
@editorialbot generate my checklist

**Comment by dstansby** [comment]
👋 all. I've completed my review, and opened several issues that I think need to be resolved - these are linked in the original issue above that I've edited.

**Comment by dfm** [comment]
@dstansby, @samaloney — I wanted to check in with both of you about the status of your reviews. Please let us know here if there are major stoppers!

**Comment by dstansby** [comment]
Just checked everything, and it's all good from my point of view now 👍

**Comment by dfm** [comment]
Thanks @dstansby!

Hopefully @samaloney can also wrap up his review soon too!

**Comment by samaloney** [comment]
Sorry for the delay looks ok to me too.

Shouldn't hold up the review but trying to run the FieldIntegration.ipynb example gives an error about missing dependancy `kaleido`.  While just commenting out the `pio.write_image(fig, '....')` call allows the notebook to run there are no figure outputs as there are no `fig.show()` calls, same in the other notebooks too.

**Comment by dfm** [comment]
Awesome! Thanks @samaloney and @dstansby!!

@asherp: I'm going to do a quick pass through everything (it shouldn't take long!) and then I'll have some proofs and final steps for you.

**Comment by dfm** [comment]
@editorialbot generate pdf

**Comment by dfm** [comment]
@asherp — I've opened a PR with some minor edits to the paper. After merging or responding to that, here are the final steps that I'll need from you:

1. Comment `@editorialbot generate pdf`, and take one last read through the manuscript to make sure that you're happy with it (it's harder to make changes later!), especially the author names and affiliations. I've taken a pass and it looks good to me!
2. Increment the version number of the software and report that version number back here.
3. Create an archived release of that version of the software (using Zenodo or something similar). _Please make sure that the metadata (title and author list) exactly match the paper._ Then report the DOI of the release back to this thread.

Thanks all!

**Comment by dfm** [comment]
@editorialbot generate pdf

**Comment by dfm** [comment]
@editorialbot check references

**Comment by dfm** [comment]
@editorialbot set 22.6.0 as version

**Comment by dfm** [comment]
@editorialbot recommend-accept

**Comment by dfm** [comment]
@asher-pembroke — I've now handed this off to the managing editors to do the final processing. There may be some final edits or other changes, but the process should be fairly quick. Thanks again for your submission and for your responses to all the suggestions from @dstansby and @samaloney!

@dstansby, @samaloney — Thanks again for your reviews of this submission. Thanks for the time that you took and the thorough and constructive comments that you made. We couldn't do this without you, and I really appreciate you volunteering your time!!

**Comment by lrastaet** [comment]
Please correct the reference for the Weierstrass function:
Correct spelling of "Werth", "Differentialquotienten" in the title and supply the full title of the book and full name and location of the publisher.

Karl Weierstrass, ["Über continuirliche Functionen eines reellen Arguments, die für keinen Werth des letzteren einen bestimmten Differentialquotienten besitzen,"](https://books.google.com/books?id=1FhtAAAAMAAJ&pg=PA71#v=onepage&q&f=false) (On continuous functions of a real argument which possess a definite derivative for no value of the argument) in: Königlich Preussichen Akademie der Wissenschaften, Mathematische Werke von Karl Weierstrass (Berlin, Germany: Mayer & Mueller, 1895), vol. 2, pages 71–74.;

**Comment by asher-pembroke** [comment]
@editorialbot generate pdf

**Comment by asherp** [comment]
@editorialbot generate pdf

**Comment by dfm** [comment]
@lrastaet, @asherp / @asher-pembroke — let me know when you're happy with the updated proofs!

**Comment by arfon** [comment]
@editorialbot recommend-accept

**Comment by arfon** [comment]
> @lrastaet, @asherp / @asher-pembroke — let me know when you're happy with the updated proofs!

:wave: from your friendly EiC. We'll hold off publishing until we've heard that folks are happy with the paper.

**Comment by danielskatz** [comment]
👋 @lrastaet, @asherp / @asher-pembroke - how does the new proof look?  Are we ready to publish?

**Comment by asher-pembroke** [comment]
@editorialbot generate pdf

**Comment by arfon** [comment]
> On page 2 of the manuscript ('Usage' chapter) the computer code shown does not yet have the corrected Weierstrass citation ( spelling in the title of the work, full book title and publisher as in the References). @asher-pembroke / @asherp - your updated version you sent me on 7/6 is OK. Please submit that one.

@asher-pembroke @lrastaet – is this fixed now? If so, can we go ahead and publish?

**Comment by lrastaet** [comment]
Yes, the issue has been fixed. You can go ahead and publish.

**Comment by arfon** [comment]
@editorialbot recommend-accept

**Comment by arfon** [comment]
@editorialbot accept

**Comment by arfon** [comment]
@dstansby, @samaloney – many thanks for your reviews here and to @dfm for editing this submission! JOSS relies upon the volunteer effort of people like you and we simply wouldn't be able to do this without you ✨ 

@asherp – your paper is now accepted and published in JOSS :zap::rocket::boom:
