### ISSUE TITLE
[REVIEW]: Parallel and Adaptive High-Dimensional Numerical Integration

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#437]
**Submitting author:** @iljah (<a href="http://orcid.org/0000-0002-9542-5866">Ilja Honkonen</a>)
**Repository:** <a href="https://github.com/iljah/hdintegrator" target ="_blank">https://github.com/iljah/hdintegrator</a>
**Version:** 0.1
**Editor:** @danielskatz
**Reviewer:** @marksantcroos
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1116815" target="_blank">10.5281/zenodo.1116815</a>

## Status

[![status](http://joss.theoj.org/papers/2ee0aa65a240628b53f298cd077e5025/status.svg)](http://joss.theoj.org/papers/2ee0aa65a240628b53f298cd077e5025)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/2ee0aa65a240628b53f298cd077e5025"><img src="http://joss.theoj.org/papers/2ee0aa65a240628b53f298cd077e5025/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/2ee0aa65a240628b53f298cd077e5025/status.svg)](http://joss.theoj.org/papers/2ee0aa65a240628b53f298cd077e5025)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/iljah/hdintegrator" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@marksantcroos, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @danielskatz know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/iljah/hdintegrator">repository url</a>?
- [x] **Version:** Does the release version given match the GitHub release (0.1)?
- [x] **Authorship:** Has the submitting author (@iljah) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license? [#4](https://github.com/iljah/hdintegrator/issues/4)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation? [#5](https://github.com/iljah/hdintegrator/issues/5) [#9](https://github.com/iljah/hdintegrator/issues/9)
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is? [#7](https://github.com/iljah/hdintegrator/issues/7)
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution. [#1](https://github.com/iljah/hdintegrator/issues/5)
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)? [#8](https://github.com/iljah/hdintegrator/issues/8)
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified? [#6](https://github.com/iljah/hdintegrator/issues/6)
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @marksantcroos it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by danielskatz** [comment]
@marksantcroos - this is ready for you to review.

An informal guideline is that we would like your review in 2 weeks, but sooner (or later) are also ok.

Please carry out your review in this issue by updating the checklist above (please make sure you're logged in to GitHub)

The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines

Please avoid lengthy details of difficulties in this review thread. Instead, please create a new issue in the target repository and link to those issues (especially acceptance-blockers) in this review thread. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

Any questions/concerns, please let me know.

Thanks!!

**Comment by danielskatz** [comment]
Hi @marksantcroos - Any news on this?

**Comment by danielskatz** [comment]
Some comments from Paul Zimmerman that may help in the review process:

> The full paper is not a long paper. The review is most of the software.
>
> Starting from the issue (https://github.com/openjournals/joss-reviews/issues/429),
the paper is in the repository as paper.md
(https://github.com/iljah/hdintegrator/blob/master/paper.md). A PDF will be
generated if/when accepted.
> 
> And again, the review is more of the software than the paper, but does include
both. See the review info in the about page
(http://joss.theoj.org/about#reviewer_guidelines), and see an example of a review
in progress: https://github.com/openjournals/joss-reviews/issues/407

**Comment by danielskatz** [comment]
Hi @marksantcroos - How's this going?

**Comment by marksantcroos** [comment]
Hi @danielskatz, sorry for the delay. I actually have a question. I played around initially, but ran into some issues that stopped me from being able to continue. I meant to read more about the process but postponed that ... Is the process meant to be incremental, or should I do it based on the status quo? E.g., if the installation stops me from continuing, is that then the end-result of the first review, or should I wait for the author to fix it? (Assuming I create issues during my review)

**Comment by danielskatz** [comment]
Don't think of this as a first review, but as an incremental process.  Report problems to the author.

- If brief, report them here

- If detailed, open an issue in the source repo and make a note here that you have done so with a link to the issue(s).

Then you are done until the author responds...

**Comment by danielskatz** [comment]
Some comments from Paul Zimmerman that might help the review process:

> Reviewer: Paul Zimmermann
> 
> This review is on revision 97f76c6c224c2433e32c8d3d03f640188e63a290
> (git clone https://github.com/iljah/hdintegrator.git).
> 
> I was told by the editor (Daniel Katz) that there would be both a paper and
> a software to review, but the paper (file paper.md) is very short: it only
> consists of 36 lines. This "paper" mentions that hdintegrator was developed
> because "none [FOSS packages for numerical integration] support parallel
> integration in arbitrary number of dimensions". It would make sense to at
> least mention in the paper some examples of integrals computed with
> hdintegrator, with timings and discussing the accuracy of the result,
> and to compare timings and accuracy to other software tools. Also the
> References part of the paper is empty.
> 
> The README file says that mpi4py is needed, but it is not explained how to get
it (say in Debian or Ubuntu).
> 
> I tried the example in README but could not make it work:
> 
> $ mpiexec -n 5 ./main_mpi.py --integrator integrands/N-sphere.py --dimensions 2
> Couldn't import required submodule(s), did you clone them with:
> 
> git clone --recursive https://github.com/iljah/hdintegrator.git
> Couldn't import required submodule(s), did you clone them with:
> 
> git clone --recursive https://github.com/iljah/hdintegrator.git
> - - - - 
> Primary job  terminated normally, but 1 process returned
> a non-zero exit code.. Per user-direction, the job has been aborted.
> - - - - 
> - - - - 
> mpiexec detected that one or more processes exited with non-zero status, thus causing
> the job to be terminated. The first process to do so was:
> 
>  Process name: [[23694,1],0]
>  Exit code:    1
> 
> My opinion is that this paper is not ready for publication, and the software
> is not ready either. The paper should include at least a few examples of
> multiple integration with timings, accuracy, and comparison to other
> multi-dimensional integrators. The software should include detailed
> instructions about pre-requisites, and better explanations in case of error.
> 
> Moreover, on http://joss.theoj.org/about#reviewer_guidelines best practices
> are mentioned: documentation, tests, continuous integration, and a license.
> While I see the license (file COPYING), I could not find the documentation
> about how to define a function to be integrated, I did not see a "tests"
> directory, and I did not see any continuous integration link.

**Comment by danielskatz** [comment]
In general, Paul's comments are inputs to you and @marksantcroos.  I don't think these discussions that Paul mentions are needed in paper.md, but they probably are needed somewhere in the documentation/repository, in my opinion.

Please feel free to ignore the references comment - Paul is new to the JOSS system.  Your understanding is correct.

**Comment by iljah** [comment]
mpi4py appears to be available in Ubuntu repositories so it should be installable as described in Ubuntu documentation: https://help.ubuntu.com/stable/ubuntu-help/addremove-install.html I don't use Ubuntu myself but I'll mention this and add the required command line incantations to the INSTALL file.

Looks like the installation instructions forgot to mention that the PYTHONPATH environment variable must include the directory of the required submodules that git clone --recursive downloads, I'll see if I can work around that within the program itself. If I cannot, I'll add a mention of updating PYTHONPATH to the INSTALL file. In case of other technical problems I suggest opening an issue in the hdintegrator repo so that others might find them, and their solutions, more easily.

The README file describes how the main program communicates with the program that does evaluates the integrals but I'll add a concrete example of how one could define a function to be integrated.

**Comment by iljah** [comment]
The program should work now without requiring manual editing of PYTHONPATH and I also added the NetworkX package as a requirement that I had forgotten to mention. I couldn't get the program to work with a vanilla install of Ubuntu but this seems to be a known bug for over a year now that is still unresolved: https://bugs.launchpad.net/ubuntu/+source/mpi4py/+bug/1583432 There's a workaround in the bug report but I didn't test it.

I added a mention of the required packages' names and a note that are different versions available for different openmpi implementation and python versions.

**Comment by danielskatz** [comment]
@marksantcroos - do you have an updated status for this review?

**Comment by marksantcroos** [comment]
Sorry for the delay again. I've completed my pass now. Ball is back to @iljah. Happy to work with you on resolving the issues.

**Comment by iljah** [comment]
Thanks, I'll start going through them...

**Comment by danielskatz** [comment]
thanks @marksantcroos and @iljah

For the record, the pass by @marksantcroos led to this set of issues in the code repo:

- https://github.com/iljah/hdintegrator/issues/1
- https://github.com/iljah/hdintegrator/issues/2
- https://github.com/iljah/hdintegrator/issues/3
- https://github.com/iljah/hdintegrator/issues/4
- https://github.com/iljah/hdintegrator/issues/5
- https://github.com/iljah/hdintegrator/issues/6
- https://github.com/iljah/hdintegrator/issues/7
- https://github.com/iljah/hdintegrator/issues/8

**Comment by iljah** [comment]
I think I managed to fix the identified issues, if not feel free to reopen or create new ones.

**Comment by danielskatz** [comment]
@marksantcroos - How do things look now?

**Comment by marksantcroos** [comment]
Managed to run some of the python-only examples now, so thats progress!

**Comment by danielskatz** [comment]
new issues:
- https://github.com/iljah/hdintegrator/issues/9
- https://github.com/iljah/hdintegrator/issues/10
- https://github.com/iljah/hdintegrator/issues/11
- https://github.com/iljah/hdintegrator/issues/12

**Comment by danielskatz** [comment]
@marksantcroos - while you don't need to list each issues here (as I am doing for completeness) can you add a comment in this review issue when you have opened issues in the source repo, so that an editor (like me) can see where things are by just looking at this issue?  Thanks!

**Comment by marksantcroos** [comment]
@danielskatz Ack. Note that I've been (trying) to maintain a list of issues in the checklist above. I think the system could be of more help to us with some reworking. Happy to share my thoughts there.

**Comment by danielskatz** [comment]
I see - I didn't notice that, as I was just scanning the checklist to see if the boxes were getting checked, not realizing that you might add notes to the items.

Your suggestions are very welcome.  Please either open an issue at https://github.com/openjournals/joss/issues or if you are feeling brave, you can edit code and make a PR in that repo as well.

**Comment by iljah** [comment]
Fixed issues 9 to 12, thanks!

**Comment by iljah** [comment]
@marksantcroos can you spot any other issues?

**Comment by marksantcroos** [comment]
@iljah I still need to test your latest changes to get the C++ stuff compiled.

**Comment by danielskatz** [comment]
Hi @marksantcroos - any update on this?

**Comment by marksantcroos** [comment]
I updated iljah/hdintegrator#10 and iljah/hdintegrator#12, and added a new iljah/hdintegrator#13.

**Comment by iljah** [comment]
Thanks, fixed 10 and 12 but I need more info for 13 because the command that failed for you worked for me.

**Comment by marksantcroos** [comment]
While we are working on iljah/hdintegrator#13, I created iljah/hdintegrator#14.

**Comment by iljah** [comment]
All issues have been closed again, @marksantcroos have you found any additional issues?

**Comment by marksantcroos** [comment]
@iljah  I just went over everything again and I've checked off all boxes. Looking back at when we started you've made quite some progress with the project!

@danielskatz What now?

**Comment by iljah** [comment]
Glad to hear! I'll create a tag in the repository and update the pypi version.

**Comment by danielskatz** [comment]
@iljah - next we need the DOI to an archived version of the current software

And @marksantcroos - thanks! you've made a good contribution to the software, the paper, and the journal.

**Comment by iljah** [comment]
I've created a DOI for the archive at Zenodo: 10.5281/zenodo.1116815

**Comment by danielskatz** [comment]
@whedon set 10.5281/zenodo.1116815 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1116815" target="_blank">10.5281/zenodo.1116815</a> is the archive.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00437/joss.00437/10.21105.joss.00437.pdf
```

**Comment by danielskatz** [comment]
@arfon - I think this is ready for you to accept

**Comment by arfon** [comment]
@marksantcroos - many thanks for your review here and to @danielskatz for editing this submission ✨ 

@iljah - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00437 ⚡️ 🚀 💥

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00437/status.svg)](https://doi.org/10.21105/joss.00437)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00437/status.svg)](https://doi.org/10.21105/joss.00437)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://bit.ly/joss-reviewers

**Comment by iljah** [comment]
Thanks all!
