### ISSUE TITLE
[REVIEW]: Missingno: a missing data visualization suite

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#547]
**Submitting author:** @ResidentMario (<a href="http://orcid.org/0000-0002-0066-5825">Aleksey Bilogur</a>)
**Repository:** <a href="https://github.com/ResidentMario/missingno" target ="_blank">https://github.com/ResidentMario/missingno</a>
**Version:** 0.4.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** @rhiever
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1184723" target="_blank">10.5281/zenodo.1184723</a>

## Status

[![status](http://joss.theoj.org/papers/52b4115d6c03864b884fbf3334851322/status.svg)](http://joss.theoj.org/papers/52b4115d6c03864b884fbf3334851322)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/52b4115d6c03864b884fbf3334851322"><img src="http://joss.theoj.org/papers/52b4115d6c03864b884fbf3334851322/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/52b4115d6c03864b884fbf3334851322/status.svg)](http://joss.theoj.org/papers/52b4115d6c03864b884fbf3334851322)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ResidentMario/missingno" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions
---
### REVIEWER 1
@rhiever, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @Kevin-Mattheus-Moerman know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ResidentMario/missingno">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (0.4.0)?
- [x] **Authorship:** Has the submitting author (@ResidentMario) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

---
### REVIEWER 2 
@zkamvar, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @Kevin-Mattheus-Moerman know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ResidentMario/missingno">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.4.0)?
- [x] **Authorship:** Has the submitting author (@ResidentMario) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @rhiever it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #547 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0     90      0 --:--:-- --:--:-- --:--:--    90
Could not find bibliography file: paper.bib
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @rhiever as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @rhiever

**Comment by Kevin-Mattheus-Moerman** [comment]
@rhiever and @zkamvar thank you for acting as reviewers! 🚀 

There are two sets of tick boxes at the top of this issue, one for each of you. If you have minor comments to the author feel free to make them here. For bigger issues you may want to open an issue on this projects [repository](https://github.com/ResidentMario/missingno) which you can refer to here in the review issue. 
Let me know if you have any questions. Also let me know if you are unable to tick the boxes.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @zkamvar as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @zkamvar

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @rhiever as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @rhiever

**Comment by Kevin-Mattheus-Moerman** [comment]
Apologies for the messages. The system is a bit rusty for multiple reviewers.

**Comment by Kevin-Mattheus-Moerman** [comment]
@ResidentMario I've opened an issue about expanding your paper [here](https://github.com/ResidentMario/missingno/issues/43). Let me know if you have questions.

**Comment by ResidentMario** [comment]
@Kevin-Mattheus-Moerman Quick question: the review instructions cite version 0.3.7, but the package is currently at version 0.3.8. What's the fix?

@zkamvar Can you link me to the R package you cited [here](https://github.com/openjournals/joss-reviews/issues/443#issuecomment-360814979)? I've lost my reference to it and want to add it to the references per [this comment](https://github.com/openjournals/joss-reviews/issues/443#issuecomment-345572443).

**Comment by zkamvar** [comment]
Hi @ResidentMario, The citation for the package (which includes the reference for the missingno function) is here: https://peerj.com/articles/281/, though I think it would be better to [cite the SciPy packages](https://scipy.org/citing.html) you import (I'll open an issue for this).

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00547/joss.00547/10.21105.joss.00547.pdf
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@ResidentMario @zkamvar @rhiever 
[📖 The paper](https://github.com/openjournals/joss-papers/blob/joss.00547/joss.00547/10.21105.joss.00547.pdf) now renders as a PDF. I've added starting commenting and providing recommendations on the paper in [this issue](https://github.com/ResidentMario/missingno/issues/43). Feel free to join there in relation to purely the paper.

**Comment by zkamvar** [comment]
I have opened an issue (https://github.com/ResidentMario/missingno/issues/45) regarding the inclusion of example data internal to the package.

**Comment by zkamvar** [comment]
I have opened an issue (https://github.com/ResidentMario/missingno/issues/46) regarding tests on non-visualization functions.

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon the author (@ResidentMario) asked 

> Quick question: the review instructions cite version 0.3.7, but the package is currently at version 0.3.8. What's the fix?

Can you help update the version listed or can the user or I do this ourselves?

**Comment by zkamvar** [comment]
Question for @Kevin-Mattheus-Moerman: When I'm finished with the review, would you like me to give a brief summary of my assessment (e.g.: https://github.com/openjournals/joss-reviews/issues/514#issuecomment-357365641)?

**Comment by Kevin-Mattheus-Moerman** [comment]
@zkamvar yes that would be good thank you.

**Comment by zkamvar** [comment]
@ResidentMario, this is a fantastic package. It is straightforward enough that I was able to use it for my own data without much effort 😃👍. The documentation is clear and the examples are wonderful for showing the utility of the package. Because of a lack of tests (though this is partially explained in the CONTRIBUTING.md file), and citations to relevant python software, I would recommend this for acceptance with **minor revisions**.

### Good points

 - easy to install with pip
 - built on top of existing, trusted packages
 - easy to use
 - clearly documented

### Blockers

 - [ ] no tests for testable functions (https://github.com/ResidentMario/missingno/issues/46)
 - [ ] paper needs citations to relevant packages (https://github.com/ResidentMario/missingno/issues/44)

### Good to have

 - [ ] a small example data set packaged with missingno  for quick demonstration and testing. (https://github.com/ResidentMario/missingno/issues/45)

<details>
<summary>My Python setup (3.4.4)</summary>

```
Python 3.4.4 |Anaconda custom (x86_64)| (default, Jan  9 2016, 17:30:09)
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```
</details>

**Comment by rhiever** [comment]
Thank you for the great package, @ResidentMario. I was able to run and verify most of the examples from the README and can clearly see the utility of this package for my own work. Based on my evaluation of the package, I recommend several **minor revisions** as listed below.

### Good points

* easy installation via pip
* clean, useful plots right out of the box
* good documentation and examples
* minimal dependencies, and the dependencies are commonly-used packages

### Blockers

Agree with @zkamvar's blockers. Adding my own:

- [ ] Create a development branch on the repo (https://github.com/ResidentMario/missingno/issues/48)
- [ ] Add grid lines to the heatmap for interpretability (https://github.com/ResidentMario/missingno/issues/50)
- [ ] Fix / address heatmap reproducibility bug (https://github.com/ResidentMario/missingno/issues/51)
- [ ] Fix / address issues with `geoplot` function not working (https://github.com/ResidentMario/missingno/issues/59)
- [ ] Address `geoplot` function imports (https://github.com/ResidentMario/missingno/issues/60)

### Good to have

Strong 👍 on @zkamvar's suggestion of having a small example dataset for the examples. I might even elevate that issue to a Blocker.

- [ ] Unit tests for dataviz functions (idea: https://github.com/ResidentMario/missingno/issues/47)
- [ ] Add more useful badges to the repo (https://github.com/ResidentMario/missingno/issues/49)
- [ ] Sort out whether `shapely` and `descartes` are actually optional dependencies (https://github.com/ResidentMario/missingno/issues/52)
- [ ] Change `inline` parameter default to `False` (https://github.com/ResidentMario/missingno/issues/53)
- [ ] Shorten and refine the README and create separate docs pages (https://github.com/ResidentMario/missingno/issues/54)
- [ ] Move `__version__` variable out of the main source file (https://github.com/ResidentMario/missingno/issues/55)
- [ ] Break up helper functions and plotting functions into separate files (https://github.com/ResidentMario/missingno/issues/56)
- [ ] Decide on usage of ' and " (https://github.com/ResidentMario/missingno/issues/57)
- [ ] Clean up code comments (https://github.com/ResidentMario/missingno/issues/58)
- [ ] Add continuous integration + testing (https://github.com/ResidentMario/missingno/issues/61)
- [ ] Add test coverage and code quality trackers (https://github.com/ResidentMario/missingno/issues/62)

<summary>My Python setup (3.6.4):</summary>
<details>

```
Python 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 12:04:33) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.
```
</details>

**Comment by ResidentMario** [comment]
@zkamvar @rhiever I've addressed the bulk of your code comments. You should take a look at the library again (open new issues etcetera), as it's changed significantly in the process.

My current plan is to finish up the library work that was uncovered in the review process and publish a `0.4.0` version with the changes. I'll finish up the remaining comments on the paper last.

**Comment by Kevin-Mattheus-Moerman** [comment]
@ResidentMario about: 
> My current plan is to finish up the library work that was uncovered in the review process and publish a 0.4.0 version with the changes.

Sounds good. I recommend minting this new version once we are good to accept. That way the paper/DOI will also point to your latest version and it wont be behind on any final edits.

**Comment by Kevin-Mattheus-Moerman** [comment]
@zkamvar @rhiever has @ResidentMario addressed your comments sufficiently?

**Comment by rhiever** [comment]
I've checked off the items on my list that have been addressed.

**Comment by Kevin-Mattheus-Moerman** [comment]
@rhiever thanks for the update. Also thanks for the very thorough review! 🦈

**Comment by zkamvar** [comment]
Hi! Yes, @ResidentMario has addressed my comments 😃.

**Comment by ResidentMario** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00547/joss.00547/10.21105.joss.00547.pdf
```

**Comment by ResidentMario** [comment]
I believe the other remaining non-paper issues have been addressed. I've finished tweaking the paper to my understanding of it, but:

* It's been a long time since I've used BibTeX so I'm not sure I've got the citations formatted right. Is it SOP that they aren't showing up in the pre-render `whedon` is generating?
* Maybe including examples of all of the plots is too much for the paper, lengthwise. missingno#43

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00547/joss.00547/10.21105.joss.00547.pdf
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@ResidentMario your .bib file looks good. It just looks like you are not citing the articles in the paper. You cite them like this for instance: 
`[@pandas]`

**Comment by ResidentMario** [comment]
D'oh. Let me fix that...

**Comment by ResidentMario** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00547/joss.00547/10.21105.joss.00547.pdf)

**Comment by rhiever** [comment]
Meant to note here that all of my blockers have been resolved, so this paper has my 👍.

**Comment by ResidentMario** [comment]
@Kevin-Mattheus-Moerman I've made the corrections to the paper in [missingno#43](https://github.com/ResidentMario/missingno/issues/43). I've also pushed the new version, 0.4.0 to PyPi. The version under review should be updated to 0.4.0, but I'm not sure how to do that. Let me know if there's anything else that needs doing (cc @zkamvar: the paper references have been resolved).

**Comment by zkamvar** [comment]
@ResidentMario, my blockers have been resolved 👍 

The only recommendation I have left would be to name the packages explicitly in text with the citation, for which I've created a PR.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00547/joss.00547/10.21105.joss.00547.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon can you help with this: 

> The version under review should be updated to 0.4.0, but I'm not sure how to do that.

**Comment by Kevin-Mattheus-Moerman** [comment]
@ResidentMario can you work on @zkamvar 's [PR](https://github.com/ResidentMario/missingno/pull/64), seems like a good suggestion.

**Comment by ResidentMario** [comment]
Done. :heavy_check_mark:

**Comment by arfon** [comment]
> @arfon can you help with this

👍 done

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00547/joss.00547/10.21105.joss.00547.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@ResidentMario looks like we are good to proceed. 🚀   

Can you please make the DOI of the reviewed software available? That way we can continue to process acceptance of this submission.

**Comment by ResidentMario** [comment]
> the DOI of the reviewed software available

Apologies---what do you mean by this? A little unclear to me. :)

**Comment by Kevin-Mattheus-Moerman** [comment]
Basically you have to archive your work on a repository with a DOI. 

See here: http://joss.theoj.org/about#author_guidelines
> Upon successful completion of the review, deposit a copy of your (updated) repository with a data-archiving service such as Zenodo or figshare, issue a DOI for the archive, and update the review issue thread with your DOI.

I use Zenodo (but other services like figshare can be used as well) and these steps: https://guides.github.com/activities/citable-code/

Once you have a DOI link paste it here. Let me know if you need help.

**Comment by Kevin-Mattheus-Moerman** [comment]
@ResidentMario how are you doing? Have you been able to archive the reviewed software in a service like [Zenodo](https://zenodo.org/) (again these steps are handy: https://guides.github.com/activities/citable-code/). One you provide the archived version DOI we can move on to the next steps.

**Comment by Kevin-Mattheus-Moerman** [comment]
@rhiever @zkamvar to wrap things up would you be able to tick the remaining boxes at the top of this issue?

**Comment by rhiever** [comment]
Two of my non-blockers have yet to be addressed (still unchecked), but I approve the paper/package regardless.

**Comment by ResidentMario** [comment]
@Kevin-Mattheus-Moerman Sorry, that this took a bit to get around to. Here it is:

Here's the DOI badge: [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.1184723.svg)](https://doi.org/10.5281/zenodo.1184723)

**Comment by Kevin-Mattheus-Moerman** [comment]
Great thanks. @arfon over to you

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1184723 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1184723" target="_blank">10.5281/zenodo.1184723</a> is the archive.

**Comment by arfon** [comment]
@rhiever - many thanks for your review here and to @Kevin-Mattheus-Moerman for editing this submission.

@ResidentMario - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00547 ⚡️:rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00547/status.svg)](https://doi.org/10.21105/joss.00547)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00547/status.svg)](https://doi.org/10.21105/joss.00547)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by Kevin-Mattheus-Moerman** [comment]
@zkamvar thank you also for your review!
